.github/workflows/build.yml, docker-compose-dev.yml, docker-compose-e2e.yml
**Current behavior**
Current `docker-compose.yml` is applicable only for e2e tests. It should provide good first installation experience instead
**New behavior**
- `docker-compose.yml` was moved to `docker-compose-e2e.yml`
- Original `docker-compose.yml` doesn't include `mwdb-tests` service and sets Docker volumes for PostgreSQL database and uploads directory.
=> Docker-compose for production envs and separate one for e2e tests

resources/object.py
- ObjectChildResource requires `adding_parents` capability
- Requirement handled via `has_rights` method instead of `@requires_capabilities` decorator.
- ObjectChildResource uses `@requires_capabilities` decorator just like the other methods.
**Test plan**
- Possible permission break already covered by automated tests
=> Use `@requires_capabilities` in ObjectChildResource 

core/service.py, resources/share.py
ShareResource accepts the variant without arguments (`/share` instead of `/<type>/<identifier>/share`) which returns only list of our own `groups` (groups that we can share object with).
This variant incorrectly reuses the ShareResource:
- accepts `PUT /share` which doesn't have any sense
- can't be covered by OAS3 documentation and rendered correctly by Swagger (Swagger renders only the `/share` variant)
Both mwdblib and web uses only `/<type>/<identifier>/share` variant. If we want to share object with group, we still need the access to this object (precondition that must be fulfilled).
Currently `/<type>/<identifier>/share` returns both list of groups and list of shares for specified object.
**What is the new …
=> Remove argumentless form of ShareResource (/share)

.github/workflows/build.yml
**Current behavior**
Secrets are not passed to the workflows, so CI doesn't work for pull requests from external contributors
**Fixed behavior**
- Docker images are now passed between jobs via artifacts
- When workflow is triggered by push into master (merged PR), images are pushed into Docker Hub (secrets will be available at this point).
=> Set up CI to work correctly with forks

core/service.py, resources/share.py, tests/test_sharing.py, tests/utils.py
`/share` endpoint was removed in #45 due to various issues described in PR.
> It's breaking change but endpoint doesn't seem to be used by clients.
Actually it is used by `Upload` view to determine the set of groups that user can share uploaded object with.
- Reimplemented `/share` endpoint as separate resource.
**Test plan**
- Check whether `/share` works (in Swagger)
- Check if Upload view loads correctly
=> Rollbacked /share endpoint removal required by Upload view

model/object.py
Tag adding/removing is very slow for popular tags. Processing time looks to be linearly dependent on count of tagged samples
Malwarecage performs check whether tag was already added/removed by concurrent request. Unfortunately, check is implemented by condition `self in db_tag.objects` which fetches **all tagged objects** on `db_tag.objects` attribute access (lazy-loaded by SQLAlchemy).
This additional query is too broad (because we should ask only for relationship with tagged object) and completely unnecessary because tag information is already fetched by joined relationship defined in Object entity.
```python
class Object(db.Model):
__tablename__ = 'object'
...
tags = db.relationship('Tag', …
```
=> Avoid fetching all tagged objects during tag add/remove operation

malwarefront/src/components/ShowObjectPresenter.js, malwarefront/src/components/ShowSample.js
Replace path in props
use Link component to navigate to the new tab
closes #18
=> Refactor ShowObjectPresenter to Link for tabs

malwarefront/src/components/Tag.js, malwarefront/src/styles/index.css
- Tag uses "all: unset" to override default `<a>` styling, which doesn't work correctly on Chromium and renders to something horrible.
- Applied correct styling to make related `<a>` elements look like regular text without underline and blueish color.
closes #54
=> Remove all:unset from tag's CSS style

malwarefront/src/components/UserSetPassword.js, resources/auth.py
Malwarecage allows to set longer password than 72 bytes but only the first 72 bytes are considered during authentication.
Limit user to set maximum 72 bytes password.
**Test plan**
Set long password (>72 b)
closes #49
=> Max length password validation

malwarefront/src/components/Tag.js
- Clicking on tag in object view throws exception `e.props.tagClick is not a function` and does nothing
- Clicking on tag redirects to `Recent <object_type>` view with `tag:<tag>` query
- `tagClick` property is optional, so we should check first whether callback is set
**Test plan**
- Click on tag in object view and check if it works
closes #55
=> Fix 'e.props.tagClick is not a function' after clicking tag in object view

malwarefront/src/commons/auth/actions.js, malwarefront/src/commons/auth/reducer.js, malwarefront/src/commons/ui/ProtectedRoute.js, malwarefront/src/components/Navigation.js, malwarefront/src/components/UserLogin.js, malwarefront/src/store.js
- Redirect to target page after session expiration not always works
- Query/hash part of path is trimmed, only path is stored in Redux state
- Renamed `navPath` to `prevLocation`
- All redirects to `/login` page and back to the target are handled by `authActions`
- Whole `history.location` object is passed to Redux state, not only the pathname part. This should preserve all location parts: pathname, query, hash and state
- Trying not to override the `prevLocation` by subsequent `logout` calls, triggered both by `HTTP 401` handler and ProtectedRoute
- Messages viewed in `/login` page are no longer a part of Redux state, they're moved to location state.
**Test plan**
- Login and …
=> Fixed various glitches related with redirect on successful login

.github/workflows/build.yml, docker-compose-e2e.yml, tests/frontend/Dockerfile, tests/frontend/cypress/integration/login.js, tests/frontend/cypress/plugins/index.js
- Parametrize `admin_password` used in test
- Reorder Dockerfile a bit
- Add tests to the workflow
Related with https://github.com/CERT-Polska/malwarecage/pull/66
=> Parametrize frontend tests and add to the workflow

deploy/docker/Dockerfile, deploy/docker/Dockerfile-web, deploy/docker/Dockerfile-web-dev, requirements.txt, start.sh, tests/backend/Dockerfile, uwsgi.ini
- Production environment contains two, differently configured nginx services - first in `mwdb` from tiangolo, second in `malwarefront` serving static web application and routing `/api` endpoint
- `mwdb` uses uWSGI's native support for HTTP (http-socket https://uwsgi-docs.readthedocs.io/en/latest/HTTP.html)
- `malwarefront` stays the same:
- nginx serves backend API proxy (`/api`) and static files for web application
- development environment does the same using webpack-dev-server and http-proxy-middleware
Files containing the uWSGI configuration in `tiangolo/uwsgi-nginx` (base for `tiangolo/uwsgi-nginx-flask`)
- env-based uwsgi configuration: …
=> Removed tiangolo in mwdb, used native uwsgi http-socket instead

deploy/docker/Dockerfile, requirements.txt
- ssdeep is built by downloading the sources directly from ssdeep-project instead of using BUILD_LIB option during installation of python-ssdeep library
- Bumped ssdeep to 3.4
- Used BUILD_LIB=1
=> Bump ssdeep and don't build it manually - use BUILD_LIB=1

deploy/docker/Dockerfile, gen_vars.sh, uwsgi.ini
**Current architecture**
- In production env: uWSGI http-socket exposed by `mwdb` is proxied by nginx in `malwarefront` container.
- In development env: http-socket is routed by webpack-dev-server
- In e2e tests: http-socket is used directly by python-requests library.
**Change description**
Default http-socket is not aware of `keep-alive` but still accepts HTTP/1.1 protocol so requests in e2e tests are failing randomly with `Connection reset by peer`. I don't know if `webpack-dev-server` provides a fallback to HTTP/1.0, so it would be more safe just to use `http11-socket` in uWSGI.
`tiangolo/uwsgi-nginx-flask` used uWSGI cheaper subsystem by default (which implicates `master=true`), so we need to enable `master=true` in `uwsgi.ini` as well. 
uWSGI …
=> Enable HTTP/1.1 socket and enable master process for uWSGI

app.py
- Added missing `additional_field` during first administration account creation
=> Hotfix: Missing field during creation of administration account

.github/workflows/build.yml
`docker wait` doesn't set exit code to the exit code of container. It is reported to stdout instead.
=> CI: fixed Docker wait error code handling for e2e tests

resources/auth.py
- User e-mail address is treated in case-sensitive manner during password recovery
- E-mail address can be stored case-sensitive, but comparison should be case-insensitive.
**Test plan**
- Register new user
- Try to recover password using uppercased e-mail (http://127.0.0.1/recover_password)
- Check if password recover form accepts e-mail with different case combination
=> Case-insensitive mail comparison during password recover

core/service.py, core/util.py, model/file.py, model/object.py, resources/__init__.py, resources/comment.py, resources/download.py, resources/metakey.py, resources/object.py, resources/relations.py, resources/search.py, resources/share.py, resources/tag.py, tests/frontend/cypress/integration/sample.js
- `type` argument in generic object-related endpoint is not respected. It makes a significant difference because in current version:
- `/file/<md5>/tag` doesn't work (md5 is defined only for files)
- `/file/<sha256>/tag` should return 404 if <sha256> identifier relates to another type of object (e.g. config)
- Identifier is case-sensitive in some endpoints and case-insensitive in the others.
- `type` is respected by all endpoints.
- Removed `authenticated_access`, `NotFound` exception should be thrown by resource code with appropriate message instead of generic `"Object not found"`
- object access by id treats `identifier` as case-insensitive value
- ssdeep and humanhash are no …
=> Respect 'type' argument in generic endpoints + case insensitive identifier

core/service.py, resources/tag.py, schema/tag.py
- `PUT/DELETE /{type}/{identifier}/tag` documentation was invalid
- `PUT/DELETE /{type}/{identifier}/tag` returns useless `{"modified": true/false}` response
- `GET /tag` returns empty list when no query is provided - this behavior is counterintuitive
- `GET /tag` doesn't properly escape '%' and '_' wildcards which are directly provided to LIKE query
- `GET /{type}/{identifier}/tag` uses two SQL queries for providing object tags - they're already joined during `Object.access`
- **Breaking change**: `PUT/DELETE /{type}/{identifier}/tag` returns updated list of tags instead of laconic `{modified:...}`. I think nobody relies on that response, it's not used by mwdblib nor web.
- Provided …
=> Revisited tag endpoints

core/schema.py, model/object.py, resources/share.py, schema/share.py
**What changed?**
- `PUT /{type}/{identifier}/share` returns shares including change instead of empty response
- Refactored schema to follow the convention
- Added `Object.get_shares()` method
**Test plan**
- All changes should be already covered by automated tests
- Tested sharing using mwdblib and web
=> Revisited share endpoints

core/util.py, model/file.py, resources/download.py, schema/download.py
**What's changed?**
- Moved token generation and verification to `model.File` methods (similar to`model.User` token methods)
**Test plan**
- Check if file download still works in mwdblib and web
=> Revisited download endpoints

core/service.py, resources/object.py, resources/relations.py, schema/relations.py
**What changed?**
- Refactored RelationsResource schema to follow the convention
- Rollbacked deprecation of `GET ​/{type}​/{identifier}​/relations`. It's not completely bad, it's just misused.
- Moved `PUT /{type}/{parent}/child/{child}` (ObjectChildResource) to `relations` group.
**Test plan**
- Checked if `GET ​/{type}​/{identifier}​/relations` and `PUT /{type}/{parent}/child/{child}` still works
=> Revisited relations endpoints

core/search/fields.py
Allow to search only for uploader: user
Allow to search for uploader: user or group
closes #94
=> Allow to use 'uploader:' query for groups

model/object.py
- `Object.children` relationship is added by backref, so it is available on instance-level, but we can't refer to that relationship on class-level.
- Required by #34 
- `Object.children` is defined as separate relationship, connected with `Object.parents` with `back_populates`.
Ref: https://docs.sqlalchemy.org/en/13/orm/join_conditions.html#self-referential-many-to-many-relationship
SQLAlchemy documentation proposes backref as a first choice but I don't see anything against back_populates.
**Test plan**
- Possible major problems caused by this change should be found by automated tests
- Check if existing relations are correct
- Check related features: upload with parent and adding …
=> Explicitly-defined Object.children relationship

core/search/search.py
- `parent:(file.size:5000 AND tag:costam)` throws ISE 500 with unhandled SQL exception "Error: column anon_2.object_id does not exist at character 2033"
- It seems that current version of search can't properly handle ListField and specialized field in the same subquery.
- `parent:(file.size:5000 AND tag:costam)` works as expected
=> Fix ISE 500 in 'parent:' query while querying for File and ListField

malwarecage/web/src/components/ShowConfig.js, malwarecage/web/src/components/ShowTextBlob.js
Unnecessary isAdmin prop from ShowConfig.js ShowTextBlob.js
Delete artifact in code
=> Remove isAdmin artifact from code

malwarecage/web/src/components/ShowConfig.js, malwarecage/web/src/components/ShowTextBlob.js
**What was fixed?**
- Tab switching in Config view (and possibly Blob view) doesn't work
- We're using `connected-react-router` so all connected components need to have injected router state to work properly with React History.
=> Regression fix: Config/Blob view tabs doesn't work

malwarecage/web/src/components/Attributes.js, malwarecage/web/src/components/Relations.js, malwarecage/web/src/components/ShowConfig.js, malwarecage/web/src/components/ShowObject.js, malwarecage/web/src/components/ShowSample.js, malwarecage/web/src/styles/index.css
- Showing "copy to clipboard" button on hover doesn't work correctly for nested dicts in lists
- Only `<td>` elements are hoverable in current CSS, all elements should be allowed
- Fixed "dict in list" issue
- Now, we're marking the element with `copyable` class where hover event should show the button, instead of marking the container making all td's hoverable.
=> Fixed 'copy to clipboard' hover behavior

malwarecage/web/src/components/RecentBlobs.js, malwarecage/web/src/components/RecentConfigs.js, malwarecage/web/src/components/RecentSamples.js, malwarecage/web/src/components/RecentView/RecentInnerRow.js
- Currently if there are too many tags, some of them are hidden behind ellipsis
=> Fix: Added noEllipsis attribute to Recent view for rows that shouldn't be cropped

mwdb/web/config-overrides.js
- Current Webpack script doesn't correctly find frontend plugins. By convention, their names are prefixed with `@mwdb-web/plugin-`
- Webpack is able to link web plugins
=> Fixed frontend plugin discovery

mwdb/model/object.py
- There is no ordering in `latest_config` attribute so MWDB shows arbitrary child config if sample has more than one of them.
- MWDB shows the latest config child
=> Fix: "Latest config" is not the latest one

mwdb/core/search/fields.py, mwdb/model/api_key.py, mwdb/model/blob.py, mwdb/model/object.py, mwdb/model/user.py, mwdb/schema/api_key.py, mwdb/schema/auth.py, mwdb/schema/blob.py, mwdb/schema/comment.py, mwdb/schema/object.py, mwdb/schema/quick_query.py, mwdb/schema/share.py, mwdb/schema/user.py, mwdb/schema/utils.py
- Important fact: timestamps are stored in database as offset-naive UTC timestamps (without timezone information)
- Marshmallow 3.x stopped serializing naive datetimes as UTC (https://marshmallow.readthedocs.io/en/stable/upgrading.html#datetime-leaves-timezone-information-untouched-during-serialization). Frontend still expects getting timestamps with timezone information (`+00:00`) and timestamps without that are treated as local time.
- In addition: we're not consistent in how we get current date/time (`func.now`, `datetime.now()`, `datetime.utcnow()`).
- Every "now" is using `datetime.utcnow()`
- Added custom field `UTCDateTime` that recovers the 2.x Marshmallow behavior
=> Fix: Ensure UTC timestamps everywhere and recover previous serialization

mwdb/core/capabilities.py, mwdb/resources/config.py, mwdb/web/src/components/Capabilities.js, tests/backend/test_config.py
The is no adding_configs capability so anyone can upload configs.
Only users with adding_configs capability can upload configs.
**Test plan**
Try to upload config with user that has no adding_configs capability and then try to add it with one that has.
closes #187
=> Added adding_configs capability and changing test

mwdb/web/src/components/UserUpdate.js
Set user permissions button is not visible when user doesn't have any capability
Set user permissions button is always visible
closes #212
=> Fix user permissions button visibility

docs/developer-guide.rst, mwdb/core/config.py, mwdb/core/mail.py, mwdb/templates/mwdb.ini.tmpl
Mail features are supported without authentication or StartTLS, which limits the use to a local mail server
Added support for : Username, Password and StartTLS.
All are optional, and can be set using environment variables, and are part of MWDBConfig. 
**Test plan**
Testing this feature requires actually using an external service with authentication.
Was tested manually.
closes #223
=> Add support for mail server authentication

mwdb/core/search/fields.py, mwdb/web/src/commons/helpers/search.js, mwdb/web/src/components/ShowConfig.js, tests/backend/test_search.py
- Frontend still uses wildcards for querying elements inside lists
- We don't support lists in lists
- When clicked on array element, MWDB will use
```
cfg.url*:"https://example.com/wp-content/J/"
```
syntax instead of
```
cfg:"*\"https://example.com/wp-content/J/\"*"
```
- Support for `cfg.array-in-array**:2` for querying that kind of stuff:
```
{
"array-in-array": [
[2, 3, 4],
[5, 6, 7]
]
}
```
closes #180
=> Added support for array search in frontend + backend improvements

docs/user-guide/7-Lucene-search.rst, mwdb/core/search/fields.py, mwdb/core/search/mappings.py, mwdb/web/src/commons/helpers/filesize.js, mwdb/web/src/commons/helpers/index.js, mwdb/web/src/components/RecentSamples.js, mwdb/web/src/components/ShowSample.js, mwdb/web/src/components/ShowTextBlob.js, tests/backend/test_search.py
File sizes are only shown as bytes.
File sizes are only shown in human-readable form.
**Test plan**
Check if human-readable file size form match with the original in bytes.
closes #229
=> human-readable file size frontend support

mwdb/resources/config.py
- `adding_configs` requirement for uploading configuration is not enforced if user has been used legacy upload endpoint (`PUT /config/<parent hash>`) e.g. using older version of mwdblib.
- `PUT /config/<parent hash>` returns 403 when user doesn't have `adding_configs` capability
=> Fix: Require adding_configs for legacy config upload endpoint

docker-compose-dev.yml, mwdb/core/util.py, mwdb/model/file.py, mwdb/model/object.py, mwdb/resources/object.py, requirements.txt
File access interface needs to be improved, especially when S3 storage is used. 
mwdb-core 2.0.0 stored the files using local file system, so we could assume that we're always able to return the valid path for the uploaded file. 2.1.0 introduced support for S3-compatible object storage which breaks that assumption.
The preferred way to access the file is stream, but some libraries/plugins can only use the buffer or path. That's why they use get_path to access the just uploaded file. Unfortunately, the get_path method was removed by object storage PR, because it was no longer valid.
- File upload temporarily stores the reference to the original stream object in …
=> File.get_path and other changes in File interface

mwdb/web/src/components/ShowConfig.js
Web application hangs after switch to `Static config` and `Parsed config` tabs in Detailed file/blob view
`Static config` and `Parsed config` tabs are working correctly.
Bug was caused by missing `path` property in some places where ConfigTable component is used. Now it's optional and `[]` by default.
=> Fix latest config tab

docs/conf.py, mwdb/core/search/fields.py, mwdb/resources/user.py, mwdb/version.py, mwdb/web/package-lock.json, mwdb/web/package.json, mwdb/web/src/commons/package.json, setup.py, tests/backend/test_search.py
- Bugs like #257 
- Users can see profiles of users out of their own groups (if they know the nickname). The information is not very detailed though, but it still should be considered as a bug.
- `uploader:` query works as expected
- `/profile/<user>` properly checks for user access permission.
**Review comments**
- Check another uses of `joinedload` introduced in 2.1.0: https://github.com/CERT-Polska/mwdb-core/compare/v2.0.0...v2.1.1
closes #257
=> Fix for 'joinedload' misuse introduced in 2.1.0

mwdb/web/src/components/Upload.js
Upload file form allows to select multiple files although only the first one is accepted.
Disabled multiple option in react Dropzone component.
**Test plan**
Check if the upload component work fine
closes #261
=> Fix: Disable multiple option in upload Dropzone

mwdb/schema/user.py
UserListResource tries to return too much information which results in n+1 SQL queries.
```
UserListResponseSchema {
users [
UserListItemResponseSchema {
...
groups [
GroupItemResponseSchema {
...
users [ <login> ]
admins [ <login> ]
}
]
]
}
```
Because that endpoint is used in multiple places, it slows down Manage users, Set user and Set group views.
Returning `GroupNameSchemaBase` instead of `GroupItemResponseSchema`, so `groups` collection exposes only `name` field. 
This is API breaking change, but applies only to the user management API which is usually not used directly by users. It also doesn't break the current frontend code.
**Test plan**
Check if 'Manage users' still works. …
=> Fix '/api/user' performance issues

mwdb/web/src/components/ShowObject/Views/ObjectBox.js
- `tab` and `subtab` extraction from path works only for `/<type>/<id>` paths, because param positions are hardcoded
- Tabs won't work correctly for routes that doesn't follow that path structure (e.g. `/remote/<remote_name>/<type>/<id>`)
- pathname is splitted into `routePath` and `tabPath`, so there is no need to use fixed positions for tab parameters
**Test plan**
- Check if tabs in ShowSample still work
=> ShowObject: more universal tabPath extraction

mwdb/web/src/commons/ui/RefString.js, mwdb/web/src/components/ShowObject/Views/SharesBox.js
In SharesBox there are routes to user/:login or group/:name.
Now there are Links that redirect to search with uploader field.
**Test plan**
Check sharesBox Links components, redirect to proper search query.
#294
=> Improvement: Search links instead of admin routes in SharesBox

mwdb/resources/remotes.py
It could be helpful to know which version of mwdb-core remote implementation is connecting with the remote server.
=> Expose server version in User-Agent for Remote API requests

docs/user-guide/7-Lucene-search.rst
Fix small sentence typo inside Lucene search docs
=> Docs: Typo in Lucene search

requirements.txt
**What is changed?**
- Depending on the pretty old 6.x version of click is not very convenient
- I don't really know why `pycodestyle` was a part of requirements, but it's not required anyway.
=> Bump click and remove pycodestyle from requirements

docs/remotes-guide.rst, mwdb/resources/remotes.py
- If config has embedded blobs, they must be pulled/pushed separately
- MWDB pulls/pushes all embedded blobs along with the configuration object
=> Remote: pull/push embedded blob along with the configuration

mwdb/web/src/App.js, mwdb/web/src/commons/ui/ErrorBoundary.js, mwdb/web/src/commons/ui/ProtectedRoute.js, mwdb/web/src/commons/ui/View.js, mwdb/web/src/components/AttributeUpdate.js, mwdb/web/src/components/DiffTextBlob.js, mwdb/web/src/components/ManageAttributes.js, mwdb/web/src/components/RecentView/QuickQueryAddModal.js, mwdb/web/src/components/RecentView/RecentView.js, mwdb/web/src/components/ShowGroups.js, mwdb/web/src/components/ShowObject/Actions/RelationsAddModal.js, mwdb/web/src/components/Upload.js, mwdb/web/src/components/UserLogin.js, mwdb/web/src/components/UserProfile.js
There is complete mess in error handling:
- `render()` errors are not handled correctly. In most cases, web app goes into infinite loop trying to re-render faulty view and sending lots of API requests.
- we can't easily redirect to another view with "success" message without special handling on the target site
- in some places: ErrorBoundaries, Views are used incorrectly, in the manner that was unexpected.
ErrorBoundary works correctly, so if something bad happens in `render()` - it fallbacks to a more friendly page.
Reworked `View` component. That component should be always top-level for "views" and receives success/error messages both from props and location state. To show how it …
=> Web: Reworked error/success handling a bit

mwdb/resources/__init__.py, mwdb/resources/object.py, mwdb/resources/remotes.py, mwdb/schema/group.py, mwdb/schema/remotes.py, mwdb/schema/user.py, mwdb/web/src/commons/api/index.js, mwdb/web/src/components/ShowObject/Actions/PullAction.js, mwdb/web/src/components/ShowObject/Actions/PushAction.js, mwdb/web/src/components/Upload.js
You can pull and push object remote to and share it for all your groups by default
Now it is possible to choose share mode, and the remote actions forms was improved by validation
**Test plan**
Pull/push all type of object between local and remote instance with various sharing modes
=> Remote API: Push and pull with share option

mwdb/resources/group.py, mwdb/web/src/commons/auth/provider.js
- All password-based sessions are invalidated when one of user groups are changed due to possible permission desync. This is pretty annoying, so we decided to remove it.
- Changes in groups doesn't invalidate user session. The only invalidating actions are ban of user account and password change
- Web part intercepts 403 and schedules async session refresh, so permissions will be synced ASAP after such event.
closes #138
=> User sessions are not invalidated when group has been changed

mwdb/model/group.py, mwdb/resources/group.py, tests/backend/test_multigroup_groups.py
- API returns ISE 500 when member was added/removed before
- API returns 409 Conflict in situation described above
**Test plan**
- Added automated test for that condition
=> Fix: ISE 500 on member add/remove when is already added/removed

docs/requirements.txt
- Bullet lists are broken due to regression in sphinx_rtd_theme (https://github.com/readthedocs/sphinx_rtd_theme/issues/1115)
- Pinned `docutils==0.16` as a workaround for this problem. Pin should be removed after `sphinx_rtd_theme` fix.
=> Docs: workaround for broken bullet lists

mwdb/core/plugins.py, mwdb/resources/comment.py, mwdb/resources/tag.py
No hooks are available for tags and comments creation.
New hooks are added for
1. Creating tags
2. Re-creating tags
3. Creating comments
**Test plan**
I used the following plugin for testing:
```python
import logging
from mwdb.core.plugins import PluginAppContext, PluginHookHandler
from mwdb.model import Tag, Comment, Object
logger = logging.getLogger("mwdb.plugin.test")
class TestHookHandler(PluginHookHandler):
def on_created_tag(self, object: Object, tag: Tag):
logger.info("[ES] Tag created: \n\tTag:%s (type: %s)\n\tObject: %s (type: %s)", tag, type(tag), object, type(object))
def on_reuploaded_tag(self, object: Object, tag: Tag):
logger.info("[ES] Tag reuploaded: \n\tTag:%s (type: …
```
=> Add hooks for tags and comments

mwdb/app.py, mwdb/resources/server.py, mwdb/schema/server.py, mwdb/web/src/App.js, mwdb/web/src/commons/api/index.js, mwdb/web/src/commons/config/provider.js, mwdb/web/src/components/About.js, mwdb/web/src/components/Navigation.js, mwdb/web/src/index.js
- `/api/server` exposes too much information. Some of them shouldn't be available for unauthenticated users (e.g. list of configured remotes, list of plugins etc.)
- `/api/docs` doesn't have authentication requirement
- Added `/api/server/plugins` endpoint that exposes plugin information and requires authentication
- Removed fields from `/api/server` response:
- `active_plugins`
- `remotes` (already available via `GET /api/remote`)
- `base_url` (used only on backend by e-mail registration features)
- Added authentication requirement to `/api/docs`
**Test plan**
- :heavy_check_mark: Checked remotes, About view and Docs view
closes #329
=> Limit /api/server information and add authentication requirement for /api/docs

CONTRIBUTING.md, dev/bump_version.json, dev/bump_version.py, docs/.gitignore, docs/conf.py, mwdb/version.py, mwdb/web/package-lock.json, mwdb/web/package.json, mwdb/web/src/commons/package.json, setup.py
Although current master branch contains new features under development, it has the same version number as latest release. That may be misleading for mwdb-core users.
It's a good practice to bump version with the first pull-request, so version number in `master` branch always fulfills [the semantic versioning](https://semver.org/) requirements.
- Because version bump requires to change all the 6 files that contain the version number: added helper script `dev/bump_version.py` that assists in that change.
- Added bump recommendation to CONTRIBUTING.md
- Bumped version to 2.3.0 to apply the recommendation to current master branch, which introduces new features comparing to the current …
=> Dev workflow: Bump version with the first PR that introduces change

mwdb/app.py, mwdb/resources/server.py, mwdb/schema/server.py, mwdb/web/src/App.js, mwdb/web/src/commons/api/index.js, mwdb/web/src/components/About.js, mwdb/web/src/components/Settings/SettingsView.js, mwdb/web/src/components/Settings/Views/SettingsOverview.js
- Plugin information stays in `About` page even if we have better place for that kind of info
- We don't have good starting page for administration view
- Moved plugin information to admin-restricted endpoint `GET /server/admin` as an replacement of `/server/plugins`
- UI: Moved plugin information from About to the new view
- Added SettingsOverview page available under `/settings` in Web UI
=> UI: Settings main page with overview and plugin information

mwdb/web/src/components/Settings/Views/AttributeDetails.js, mwdb/web/src/components/Settings/Views/GroupDetails.js, mwdb/web/src/components/Settings/Views/UserDetails.js
- Action nav-links navigate to `#...` because of missing `preventDefault`
- Added missing `preventDefault` invocations
=> UI: Prevent navigation to #block-user in nav-links

mwdb/web/src/commons/ui/View.js, mwdb/web/src/commons/ui/index.js, mwdb/web/src/components/Profile/ProfileView.js, mwdb/web/src/components/Profile/Views/ProfileAPIKeys.js, mwdb/web/src/components/Profile/Views/ProfileGroup.js, mwdb/web/src/components/Profile/Views/ProfileGroups.js, mwdb/web/src/components/Profile/Views/ProfileResetPassword.js, mwdb/web/src/components/Settings/SettingsView.js, mwdb/web/src/components/Settings/Views/AccessControl.js, mwdb/web/src/components/Settings/Views/AttributeDetails.js, mwdb/web/src/components/Settings/Views/AttributePermissions.js, mwdb/web/src/components/Settings/Views/AttributeView.js, mwdb/web/src/components/Settings/Views/GroupDetails.js, mwdb/web/src/components/Settings/Views/GroupMembers.js, mwdb/web/src/components/Settings/Views/GroupView.js, mwdb/web/src/components/Settings/Views/SettingsOverview.js, mwdb/web/src/components/Settings/Views/UserDetails.js, mwdb/web/src/components/Settings/Views/UserResetPassword.js, mwdb/web/src/components/Settings/Views/UserSingleGroups.js, mwdb/web/src/components/Settings/Views/UserView.js
- Setting success/error alert directly via `history` is a bit too complicated. This results in error handling inconsistency.
- Added `useViewAlert` hook that unifies error handling via location state.
- Fixed error/success handling in some places in Profile/Settings views
=> UI: Unified error/success handling via useViewAlert

mwdb/model/metakey.py
- `[url]/admin/attributes` doesn't load because request to `/api/meta/manage` takes too long. SQL query used underneath loads not only attribute keys but also attribute values
- Removed eager-loading introduced accidently in https://github.com/CERT-Polska/mwdb-core/pull/321
Thanks @ITAYC0HEN for noticing that flaw!
=> Fix: Remove eager-loading of all related object attributes in MetakeyDefinition

mwdb/core/search/fields.py
- ListField doesn't work with wildcard values due to abandoned part of code introduced in https://github.com/CERT-Polska/mwdb-core/pull/298 (dev, current stable not affected)
- Removed check that references non-existent `support_wildcards` attribute
Noticed by @ITAYC0HEN.
=> Fix: removed abandoned check in ListField

mwdb/core/plugins.py
- Migrations are designed to migrate Karton attribute into new KartonAnalysis object.
- If Karton plugin is enabled, it sets back Karton attributes resulting in incorrect behavior.
- Ignore all plugins which description starting with `Karton integration plugin`
=> Ignore Karton integration plugin in plugin loader

docs/conf.py, mwdb/version.py, mwdb/web/package-lock.json, mwdb/web/package.json, mwdb/web/src/commons/package.json, setup.py
Release Candidate version of mwdb-core 2.3.0 :tada:
This release is focused mainly on MWDB administration improvements and further UI refactoring. In addiition, Karton integration is now available out-of-the-box, without need of extra plugins.
**Key changes**:
- Read-only guest accounts (https://github.com/CERT-Polska/mwdb-core/pull/334):
- All users are by default added into additional 'registered' group that enables profile customization and file upload
- To make a guest account, just remove it from 'registered' group, so only the 'public' capabilities will apply to this group. 'public' group doesn't have any capabilities by default, but feel free to change it depending on your needs.
- All groups have additional properties: "workspace" and "default". `registered` group and `public` …
=> Bump version: 2.3.0-rc1

mwdb/web/src/commons/auth/provider.js, mwdb/web/src/commons/config/provider.js
Multiple MWDB users are reporting problems with unexpected session expiration during normal usage or after leaving the MWDB opened for a longer time.
This is pretty annoying and is caused by few flaws in client-side code that handles authentication.
This PR applies few fixes:
- Webapp periodically refreshes the session to prevent expiration when tab is opened for a longer time. Unfortunately, that mechanism caused the opposite effect, because there are huge chances that some of `/api/refresh` requests will fail after multiple periodic calls, causing the logout. Changed handling of that situation from logout to silent error reported in console. If session has really expired, user will …
=> Fix for premature session expiration

mwdb/web/src/commons/ui/Autocomplete.js
Dropdown menu buttons have not correct type. Default button type is `submit`, so they take over Enter key handling after dropdown appear.
Added `type="button"` to dropdown menu buttons, so input is correctly submitted.
closes #401
=> Fix Enter key behavior in Autocomplete list

.dockerignore, mwdb/web/.dockerignore
Non-root .dockerignore files are ignored, it doesn't work like `.gitignore` files :disappointed: 
- Moved entries from `mwdb/web/.dockerignore` to the `.dockerignore` in context root so these entries are not ignored by Docker.
=> Move mwdb/web/.dockerignore entries to .dockerignore

mwdb/web/src/components/Docs.js, mwdb/web/src/components/RelationsPlot.js
Main web bundle is huge and has almost 4MB which results in slow loading time.
SwaggerUI and DagreD3Plot (d3) components are lazy-loaded, so the main application bundle is small enough to boot quickly. 
**Test plan**
Check if Relations and Docs still work correctly.
<!-- After submitting, your code will be tested by the CI pipeline. Please
=> UI: Lazy-load DagreD3Plot and SwaggerUI

mwdb/web/src/components/Docs.js, mwdb/web/src/components/RelationsPlot.js
All lazy components are reloaded after each re-render of parent component
Moved `React.lazy` calls out of render function
=> UI: Moved React.lazy out of render() functions

docs/conf.py, mwdb/model/karton.py, mwdb/model/object.py, mwdb/resources/karton.py, mwdb/version.py, mwdb/web/package-lock.json, mwdb/web/package.json, mwdb/web/src/commons/package.json, setup.py
Karton integration added in 2.3.0 allowed only to bind Karton analysis identifiers that were already registered in MWDB by `ObjectUploader.on_created` hook. That was simple approach for initial implementation but wasn't a wise choice, because analyses can be still spawned by some external services. These analyses are currently rejected by MWDB and karton-reporter.
- MWDB creates KartonAnalysis during Karton analysis assignment when UUID was not already registered.
**Test plan**
Check if Karton integration still works correctly
=> Allow to bind unknown Karton analyses to the objects

.github/workflows/build.yml
- We don't have complete information when E2E tests for backend fail.
- CI job stores logs from `mwdb` container in artifacts after failed job
=> CI: Store logs for failed e2e backend tests

mwdb/model/blob.py, mwdb/model/config.py, mwdb/model/file.py, mwdb/model/karton.py, mwdb/model/object.py, mwdb/resources/blob.py, mwdb/resources/config.py, mwdb/resources/file.py, mwdb/resources/object.py
- Karton analysis can't be assigned during object upload
- Uploading a file with a new `karton` metakey creates and assigns a new KartonAnalysis
**Test plan**
- Try to upload file with `karton` metakey set or `karton_id` parameter
closes #431
=> Fix Karton analysis assignment during object upload

mwdb/model/object.py
- There are debug prints left after `uninherit_share` method development
- Removed debug prints
=> Remove debug prints in Object.uninherit_share

deploy/docker/Dockerfile-web, deploy/docker/Dockerfile-web-dev, docs/conf.py, mwdb/version.py, mwdb/web/package-lock.json, mwdb/web/package.json, mwdb/web/src/commons/package.json, setup.py
- `npm ci` introduced in #442 was meant to improve building time of Docker-based environment, but plugins are not installed correctly.
- Reverted to `npm install`
This branch is intentionally based on v2.5.0 and doesn't include changes from current master.
=> Revert #442: Use 'npm ci' instead of 'npm install'

mwdb/app.py, mwdb/core/karton.py, mwdb/core/search/fields.py, mwdb/core/search/mappings.py, mwdb/model/__init__.py, mwdb/model/attribute.py, mwdb/model/blob.py, mwdb/model/config.py, mwdb/model/file.py, mwdb/model/group.py, mwdb/model/migrations/versions/35916645cf47_rename_metakey_to_attribute.py, mwdb/model/object.py, mwdb/resources/blob.py, mwdb/resources/config.py, mwdb/resources/file.py, mwdb/resources/metakey.py, mwdb/resources/object.py, mwdb/resources/remotes.py
Naming problem described in https://github.com/CERT-Polska/mwdb-core/issues/301
- Renamed internal model names from `Metakey` to `Attribute`
- `schema` and `resources` intentionally left without changes: Metakey part will represent the legacy, deprecated API. Attribute is reserved for new API endpoint set.
- Plugin breaking change: related db.Object methods (`get_metakeys`) are renamed (`get_attributes`). Plugins must be adapted to that change.
**Test plan**
- Check if attribute actions work as usual
=> Rename metakeys to attributes

mwdb/core/search/fields.py
It is impossible to search files using wildcard in `karton `search field.
Single wildcard in `karton `search field is allowed. Using Lucene query `karton:*` -  returns samples for which karton analyses are attached. Using query `NOT karton:*` - gives samples without karton analysis.
closes #395
=> add search wildcard to UUIDField

mwdb/resources/__init__.py, mwdb/resources/karton.py, mwdb/resources/metakey.py
ISE 500 when non-UUID Karton identifier is added
HTTP error 400 when non-UUID Karton identifier is added.
Applied to legacy /meta behavior and new Karton endpoints as well.
closes #452
=> Add karton uuid validation

mwdb/model/object.py, tests/backend/test_api.py
Object type conflict condition is incorrectly checked:
```python
if new_cls is not isinstance(obj, cls):
new_cls = cls.get(obj.dhash).first()
if new_cls is None:
raise ObjectTypeConflictError
```
`if new_cls is not isinstance(obj, cls)` is always true because we use `is not` operator for comparing Object and bool. Conflict is still correctly checked because `_get_or_create` always try to fetch typed instance. It's unnecessary when object was just created though.
- Added correct `if not is_new` condition
- Renamed `new_cls` to `created_object` and added more comments for readability
- Added test that checks for conflict
closes #476
=> Fix: wrong conflict check in Object._get_or_create

mwdb/core/util.py, mwdb/model/migrations/versions/574bce4bac6f_zero_pad_crc32_to_8_characters.py, tests/backend/test_api.py
- CRC32 is not zero-padded to 8 bytes, which conflicts with some internal assumptions (including new `multi` feature)
- Added migration that pads CRC32 into full length as other sums and hashes
**Test plan**
- Tested migration on production-alike data whether low CRC32 are zero-padded
- Added test `test_zero_starting_crc32`
closes #493
=> Fix: zero-pad CRC32 to 8 bytes

docs/setup-and-configuration.rst
Invalid permalink for ``Alternative setup with Docker Compose`` for that documentation section.
Change title from ``Alternative setup using Docker Compose`` to ``Alternative setup with Docker Compose``.
**Test plan**
Local build docs environment and check if permalink works fine.
closes #483
=> Fix permalink to Docker section in docs

mwdb/web/src/components/Attributes.js
Can't display the name of attribute in show object view.
Maouseover text for attributes that show real name of the attribute and new button near attribute value that redirects to search with field: "meta.attribute-name:current_value".
**Test plan**
Add attributes to some objects and check if everything works properly.
closes #359
=> Add mouseover text for attributes and search button for its values

mwdb/model/attribute.py, mwdb/model/object.py, mwdb/resources/attribute.py, mwdb/web/src/commons/api/index.js, mwdb/web/src/components/AttributeKarton.js, mwdb/web/src/components/Attributes.js, mwdb/web/src/components/AttributesAddModal.js, mwdb/web/src/components/Remote/RemoteAPI.js, mwdb/web/src/components/Settings/SettingsView.js, mwdb/web/src/components/Settings/Views/AttributeCreate.js, mwdb/web/src/components/Settings/Views/AttributeDetails.js, mwdb/web/src/components/Settings/Views/AttributePermissions.js, mwdb/web/src/components/Settings/Views/AttributeView.js, mwdb/web/src/components/Settings/Views/AttributesList.js
Web client still uses old Metakey API
Web client uses new Attribute API and properly renders non-string values.
Additional bugfixes:
- fixed `remove_attribute_by_id` that disallowed to remove attributes without explicit ACLs when `adding_all_attributes` capability is set
- fixed attribute definition update endpoint throwing ISE 500
**Test plan**
- Check if all attribute-related functions still work
=> Web: use new Attribute API instead of legacy Metakey API

mwdb/web/src/components/Attributes.js, mwdb/web/src/components/AttributesAddModal.js, mwdb/web/src/components/Upload.js, mwdb/web/src/styles/index.css
- JSON attributes can't be added directly from Web
- Rendering of JSON attributes should be improved a bit
- Added option to add JSON attributes from Web
- Improved button rendering for JSON attribute options
=> Web: Adding JSON attributes from Web

.github/workflows/build.yml
- Well... Docker images are not pushed at all (due to `event` => `event_name` typo)
- Tried to adapt workflow to similar version as in https://github.com/CERT-Polska/karton-classifier/blob/master/.github/workflows/publish.yml
**Test plan**
- Check if CI correctly builds images and pushes them when branch is merged with master
=> CI: Push Docker images for master branch

.github/workflows/build.yml
Introduced `push_images` job in build workflow.
Related with https://github.com/CERT-Polska/mwdb-core/pull/503
=> CI: Separate job for pushing images

.github/workflows/build.yml
- Current CI workflow doesn't use any caching
- CI workflow tries to use `master` image from registry and GHA cache to speed up image build time
- Added correct `push --all-tags`
=> CI: Introduce layer caching with GH Actions Cache and registry

.github/workflows/build.yml, .github/workflows/release.yml, dev/bump_version.json, dev/bump_version.py, docker-compose.yml
- Docker images on Docker Hub are not tagged against the version
- Added proper version tagging to release workflow (building with cache should be faster than pulling the images)
- Pinned image version in `docker-compose.yml`
- Improved `dev/bump_version.py` script
**Test plan**
- `dev` release will be generated to check if workflow works correctly before stable `2.6.0` release.
closes #465
=> CI: Tagging Docker image with version tag on release

.github/workflows/build.yml
We have problems with CI when docker/build-push-action tries to push cache artifacts to GHA cache
```
#17 exporting cache
#17 preparing build cache for export done
#17 writing layer sha256:2fcd866b2b28912fa0b8d82b36eab616af243785ee69bbc02ea865c5b103731a
#17 writing layer sha256:2fcd866b2b28912fa0b8d82b36eab616af243785ee69bbc02ea865c5b103731a 1.2s done
#17 ERROR: error writing layer blob: Patch "https://artifactcache.actions.githubusercontent.com/ZZykNmevxKcKtilmBliEZcTNHLY9TCICy4RK7vdM3fyFYHMRag/_apis/artifactcache/caches/730": http: read on closed response body
------
> exporting cache:
------
error: failed to solve: error writing layer blob: Patch "https://artifactcache.actions.githubusercontent.com/ZZykNmevxKcKtilmBliEZcTNHLY9TCICy4RK7vdM3fyFYHMRag/_apis/artifactcache/caches/730": …
```
=> CI: Don't use GHA cache due to connection problems

mwdb/app.py
- Sometimes exception happens before `@before_request` handlers has a chance to spawn and `log_request` fails because of missing `request_start_time`
- Set `response_time` in log record extras to None if `g.request_start_time` is not available
**Test plan**
- Check if request handling still works (should be covered by automated tests)
=> Fix: set response_time to None if not available

mwdb/core/log.py, requirements.txt
Replace logmatic.JsonFormatter with direct usage of python-json-logger.
The only thing that logmatic package introduces are timestamps, enabled
by default. Call jsonlogger.JsonFormatter with timestamp=True to retain
this behavior.
**Test plan**
=> core: Drop logmatic from dependencies

.github/workflows/build.yml
- Workflows are not run for PRs that pull into `v2.x.x` backport branches
- Additional branch rule to run workflows on backport branches
=> CI: Run workflows on backport branches

.github/workflows/build.yml
- Workflows doesn't run for v2.6.x branch
- Add rule to run workflow on backport branches
=> [v2.6.x] CI: Run workflows on backport branches

mwdb/resources/user.py
When implementing email sign up and verification for the project, We will get an error if this decode method is not removed on line 141:
mwdb_1                  | [ERROR] uWSGIWorker4Core0 - service.error_router:76 - Unhandled exception occurred
mwdb_1                  | Traceback (most recent call last):
mwdb_1                  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
mwdb_1                  |     rv = self.dispatch_request()
mwdb_1                  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
mwdb_1                  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
mwdb_1                  |   File …
=> Fix regression in user.py

.github/workflows/build.yml
Images on Docker Hub are still broken, possibly due to GHA cache
Removed usage of GHA cache from build workflow
=> CI: Remove GHA cache

.github/workflows/build.yml, .github/workflows/release.yml
Our workflow produces empty images. After debugging I found that if `cache-to` uses the same tag as target image tag: target image is overwritten by cache manifest.
- Use `buildcache` tag for cache manifest pushed to Docker Hub
- Added `latest` tag for release workflow
=> CI: Use buildcache tag for cache manifest

docker/nginx.conf.template
Nginx configuration used in mwdb-web doesn't handle correctly `/api` request without trailing slash
In that case, it redirects to absolute URL with server name that might be incorrect for end user.
Added nginx rule to make a relative redirect in case of missing trailing slash
**Test plan**
Checked in Docker-Compose environment
```
$ curl http://127.0.0.1/api -vvv -L
*   Trying 127.0.0.1:80...
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET /api HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.20.2
< Date: Thu, 07 Apr 2022 13:38:51 GMT
< Content-Type: text/html
< …
```
=> Fix: handle /api endpoint without trailing slash in mwdb-web Docker

mwdb/resources/download.py
decode method in legacy download token
Pass download_token as string to function without decoding method
**Test plan**
Try to use endpoint and access token for download some file.
closes #588
=> Remove decode method from legacy download_token

mwdb/model/object.py
Described in #586: when tag already exists, nested transaction is initiated by begin_nested() but is never committed nor rollbacked. That's why the commit that is meant to commit the whole transaction, only cancels the savepoint and object gets lost.
Duplicated tag is handled correctly and rejected at the beginning of the function.
**Test plan**
closes #586
=> Fix: failed upload when duplicated tags are passed

mwdb/templates/mwdb.ini.tmpl
Timeouts are templated in `mwdb.ini.tmpl`. In the same time, values are not set by `mwdb configure` which results in wrong configuration.
- Timeout values are commented out in template with additional documentation provided
**Test plan**
Check if `mwdb configure` generates correct configuration.
closes #590
=> Fix: wrong configuration template for timeouts

mwdb/core/util.py
Described in #601 
If MagicException is raised, file_type fallbacks to `data`
closes #601
=> Fix: fallback to 'data' if MagicException is raised

mwdb/resources/blob.py, mwdb/resources/config.py, mwdb/resources/download.py, mwdb/resources/file.py, mwdb/resources/metakey.py, mwdb/resources/quick_query.py, mwdb/resources/search.py
Deprecated methods are grouped into `deprecated` tag which isn't very discoverable.
Used `deprecated` attribute from OpenAPI Spec (better described in https://github.com/CERT-Polska/mwdb-core/issues/630)
closes #630
=> Docs: mark deprecated methods using OAS3 attribute instead of tag

dev/oidc/init.py, mwdb/web/src/components/Settings/Views/OAuthProvider.js
Wrong URL in testing script for setting up Keycloak couse HTTPError.
Fixed URLs in init.py that setting up Keycloak instance and account for mwdb.
**Test plan**
Check if mwdb environment for local OpenIDConnect works properly.
closes #638
=> Fix OpenIDConnect testing script URLs and details view error

mwdb/core/config.py, requirements.txt
- Default values are casted by typed-config < 1.1.0
- Cast functions incorrectly handle empty values
- Bumped typed-config to 1.1.0 and changed default values to appropriate type
- Changed `storage_provider_from_str` to return DISK if value is empty
- Changed `path` to raise exception if value is provided but empty
**Test plan**
closes #634
=> Bump typed-config and fix default handling

dev/karton.ini, docker-compose-dev-karton.yml, docker-compose-dev-remote.yml, docker-compose-dev.yml, docker-compose-e2e.yml, docker-compose-oidc-dev.yml, mwdb/core/karton.py, mwdb/core/util.py, mwdb/model/file.py, requirements.txt
- Upgraded Karton Core to v5.0.0 and removed workarounds required because of missing `Resource(fd=...)`  in previous versions
- Moved from minio-py to boto3 (Karton v5 uses boto3 as S3 client)
**Test plan**
- Test if interaction with Minio via Boto3 works correctly (storing and downloading files)
=> Upgrade Karton Core to v5.0.0 and move from Minio-Py to Boto3

mwdb/app.py
Since the result isn't used, there is no need to keep it around.
The regex used in `HashConverter` is using a group, but since mwdb only cares whether the regex is matching or not (and not what it matches on), there is no need to keep the result around.
The match of `HashConverter`'s regex isn't kept.
**Test plan**
Simply run the testsuite
=> Don't use a group in HashConverter's regex

mwdb/web/src/components/About.js
- [c] I've read the [contributing guideline](CONTRIBUTING.md).
- [c] I've tested my changes by building and running the project, and testing changed functionality (if applicable)
Oh the ugly limy green colour!
Oh the sweet grey-ish colour, the very same that the one used for links in the navbar, which has the same background colour, making everything **much more** coherent and pleasant to the eyes!
=> Fix the colour to mwdblib's link

docker/start.sh
Docker starts MWDB server even if migration fails
`uwsgi` is run only if `mwdb-core configure` passes without error
**Test plan**
=> Fix docker/start.sh: don't run if configure fails

mwdb/schema/file.py
Hey!
I was noticing that SHA1 was missing from the API response while searching for files using [GET] /api/file and using queries for searching. While it doesn't make sense to include every type of hash in the API response, I'd argue that SHA1 is still in common use. It would reduce to the amount of API calls to fetch SHA1 hashes en-masse. 
Please let me know if it's not feasible or if there is an alternative method recommended. :)
Currently the "Search or list files" API query only returns MD5 and SHA256 hashes.
The API query now also returns SHA1 hashes.
**Test plan**
Should work from the get-go. Changes can be reproduced easily while using the Docker-based dev environment for …
=> Add "sha1" to [GET] /api/file response - "Search or list files"

mwdb/web/src/components/ShowObject/Views/AttributesBox.js
- `context.object.attributes` are already loaded in `[{key, value, id}, {key, value, id}, ...]` format
- then are reloaded by updateAttributes and converted to `{key: {value, id}, key: {value, id}}` format
- `context.object.attributes` has inconsistent format
Don't overwrite aggregated attributes in `context.object`.
=> Fix: attributes appear in two different formats in context.object

deploy/docker/Dockerfile, docker-compose-dev.yml, docker-compose.yml, docs/conf.py, mwdb/core/util.py, mwdb/version.py, mwdb/web/package-lock.json, mwdb/web/package.json, mwdb/web/src/commons/package.json, requirements.txt, setup.py
MWDB uses library ssdeep with relies on libfuzzy-dev, which complicates the building process and provides additional requirements that might be difficult to fulfill in some environments.
Instead of ssdeep I use ppdeep, which is a purely python library.
**Test plan**
closes #412
=> Replace ssdeep with ppdeep

docker-compose-dev-karton.yml, mwdb/model/file.py
File can't be reanalyzed because stream provided by File.open is not seekable
File is pre-downloaded from S3 storage into temporary file
**Test plan**
closes #693
=> Pre-download file from S3 to TemporaryFile on File.open

docs/user-guide/9-Sharing-objects.rst, mwdb/core/capabilities.py, mwdb/model/migrations/versions/c7c72fd7fac5_rename_sharing_object_capability.py, mwdb/model/object.py, mwdb/resources/__init__.py, mwdb/resources/blob.py, mwdb/resources/config.py, mwdb/resources/file.py, mwdb/resources/share.py, mwdb/web/src/commons/auth/capabilities.js, tests/backend/test_multigroup_groups.py, tests/backend/test_permissions.py, tests/backend/test_sharing.py
Name of "sharing_objects" capability is misleading. Every user can share objects. This capability allows sharing object with any other user.
Rename "sharing_objects" to "sharing_with_all"
**Test plan**
1) Test if the capability still works properly
2) Test if the migration changes capability name in database
connected to #604
=> rename sharing_objects capability

mwdb/model/object.py, tests/backend/test_permissions.py
We're unable to delete object with comments.
Problem was caused by two relationships between Object and Comment table that were trying to reconcilate the fact that Object is deleted:
- comments with `cascade="delete"` included that deletes all comments that are orphaned
- comment_authors with default cascade setting that expects comments to be not deleted because they're treated like secondary table representing many-to-many relationship between objects and users.
These actions are in conflict that can be solved using `passive_deletes=True`, because foreign key constraints have already set `ondelete` behavior.
In addition, I set `passive_deletes` on comments as well to make …
=> Fix: unable to delete objects with comments

mwdb/app.py, mwdb/model/file.py, mwdb/resources/file.py, mwdb/web/src/commons/api/index.js, mwdb/web/src/components/ShowSample.js, requirements.txt
Browser downloads and caches original content file from `preview` tab. As consequence AV or EDR engine could raise an alert for malicious content.
Default path to Chrome cache on Windows (which is indicated as threat source by AV):
- `C:\Users\<USER>\AppData\Local\Google\Chrome\User Data\Default\Cache\Cache_Data`
One of solutions could be that server send xored sample with known, fixed xor key (0xff), which is later unxored before showing it in details view. In that case cached sample will be bit-flipped file.
After preview tab is being activated, browser sends request to endpoint (`/file/<hash64:identifier>/download`). The endpoint serves a plaintext file using method `File.iterate`. Received response is cached …
=> Prevent browser from caching samples (malware)

.github/workflows/build.yml, .github/workflows/release.yml
- Emit `mwdb-web-source` from `build` stage to allow users to additionally extend it and rebuild with plugins
- Tag all images as `vx.x.x` and `latest` while doing a release
=> CI: Emit mwdb-web-source image and tag correctly images during release

mwdb/model/migrations/versions/d7725a4e500c_tag_model_flattening.py, mwdb/templates/mail/recover.txt, mwdb/templates/mail/register.txt, mwdb/web/src/App.jsx, mwdb/web/src/components/Settings/Views/UserResetPassword.jsx, mwdb/web/src/components/UserSetPassword.jsx
When resetting password user is redirected to: i.e. mwdb.cert.pl/setpasswd/<jwt_token> (token is in path)
jwt token has `.` characters in it, which causes some browser to throw an error
Instead of passing jwt token in path, I pass it using SearchParams
i.e. mwdb.cert.pl/setpasswd/?token=<jwt_token> (token is in param)
**Test plan**
Try to reset password
closes #748
=> Fix problem with jwt token when resetting password in v2.9.0

mwdb/web/src/components/RecentView/RecentView.jsx
- Can't navigate back in RecentView
- `setCurrentQuery` should be the only routine used for submitting new query
- `Count` is `type="button"` instead of `type="submit"` to not trigger the `onSubmit`. Submission relies on `submitQuery` change (with `countingEnabled` as dependency, which triggers `useEffect`
- Exception is raised when `setCurrentQuery` is called twice with the same query.
=> Fix navigation issues in RecentView

docs/setup-and-configuration.rst, mwdb/core/app.py, mwdb/core/config.py, mwdb/resources/file.py
Users can upload as big file as they want and administrator doesn't have any tools (inside MWDB) to prevent that.
Administrator can configure limit for uploaded files
Checking file's size is not precise. In order to simplify the code, I check `Content-Length` field in request header. This value is bigger that actual file size by +/- 500B.
In my opinion this error margin is acceptable - in most scenarios the limit will be set to megabytes, so even if the other values in request were 1 kB, the margin of error would be less that 0.1%
**Test plan**
Change values of `max_upload_size` in config and try to upload a file.
closes #9
=> add new field in config, check upload size

.github/workflows/build.yml, docker-compose-e2e.yml, tests/frontend/cypress/integration/blob.js
**What is behaviour?**
- Cypress videos are extracted into CI artifacts when web-tests fail
- Added fixed `container_name`s for e2e postgres, tests and web-tests containers
=> CI: Fixed e2e container names and Cypress videos

.github/workflows/build.yml, .github/workflows/release.yml
There are lots of deprecation warnings in Actions tab due to obsolete action versions. Bumped most of them to the latest version to fix that issue.
Not all of them are fixed, see https://github.com/CERT-Polska/lint-python-action/pull/6
=> CI: Bump deprecated actions

.github/workflows/build.yml
- CI fails on `master` because of wrong context for one of push tasks
- Removed `context` field to use source root as a context as expected
=> CI: Fix context in push_test_images workflow

mwdb/web/vite.config.ts
I have written `@mwdb-web/commons` resolver myself and it's pretty limited (it allows only to import packages following specific export scheme)
I used `resolve.alias` to expose core modules under `@mwdb-web` alias making them available for plugins.
It needs to be documented in https://github.com/CERT-Polska/mwdb-core/pull/761 
**Test plan**
:heavy_check_mark: Checked for example plugin added to `docker/plugins`
=> Use resolve.alias instead of custom resolver for @mwdb-web

mwdb/resources/group.py
Described https://github.com/CERT-Polska/mwdb-core/issues/839.
Current permission model is too complex to check if user actually removes `manage_users` permission from themselves.
Restriction is removed.
**Test plan**
closes #839
=> Fix: Revert self-remove of manage_users capability

docker-compose-e2e.yml, mwdb/cli/database.py, mwdb/model/group.py, mwdb/model/migrations/versions/6a7aefae72d3_rolling_back_objectpermissions_from_.py, mwdb/model/object.py, mwdb/model/user.py, mwdb/resources/tag.py, tests/backend/test_blobs.py
When new sample is added, we add new entry in `ObjectPermission` table for every user with `access_all_objects` capability
This causes that we have many unnecessary rows in this table and MWDB works slower
Additionally, it's harder to revoke access to objects, when user loses the `access_all_objects` capability
Instead of adding new rows in `ObjectPermission`, check if user has `access_all_objects` capability when querying
When user loses `access_all_objects` capability, they lose access to them (applies only in cases, when access to object is granted only by this capability) 
**Test plan**
Under development
closes #758
=> Don't query ObjectPermission table when user has access_all_objects capability

mwdb/web/src/commons/plugins/Extension.tsx, mwdb/web/src/commons/plugins/index.jsx, mwdb/web/src/commons/plugins/loader.tsx
Fixed warning:
```
#23 47.02 ✓ 3132 modules transformed.
#23 47.16 Export "Extension" of module "src/commons/plugins/Extension.tsx" was reexported through module "src/commons/plugins/index.jsx" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
#23 47.16 Either change the import in "src/components/Views/UserLoginView.tsx" to point directly to the exporting module or do not use "preserveModules" to ensure these modules end up in the same chunk.
```
and added proper types to plugin loader
=> Web: types for plugins loader, removed circular dependency

docker/mwdb.ini, docs/setup-and-configuration.rst, mwdb/app.py, mwdb/core/app.py, mwdb/core/config.py, mwdb/core/log.py
- ~~I've added automated tests for my change (if applicable, optional)~~
MWDB backend ignores `X-Forwarded-For` header and `remote_addr` always points at the remote from direct connection.
It breaks rate limiting of unauthenticated requests.
Added `use_x_forwarded_for` that optionally applies ProxyFix (https://flask.palletsprojects.com/en/2.3.x/deploying/proxy_fix/). It's set by default to 1 in `docker/mwdb.ini` file.
closes #844
=> Add use_x_forwarded_for option that applies ProxyFix to correctly handle X-Forwarded-For header

docker-compose.yml, docs/conf.py, mwdb/core/karton.py, mwdb/version.py, mwdb/web/package-lock.json, mwdb/web/package.json, requirements.txt, setup.py
- `quality` and `share_3rd_party` headers must be explicitly proxied by all Karton services in pipeline
- Using new Persistent headers feature from v5.2.0 to make headers that will apply to whole analysis.
=> Use Karton persistent headers for 'quality' and 'share_3rd_party'

mwdb/web/src/commons/ui/HexView.tsx
- ~~[ ] I've added automated tests for my change (if applicable, optional)~~
- ~~[ ] I've updated documentation to reflect my change (if applicable)~~
- MWDB web crashes after switching to `hex` mode in Preview
- MWDB web crashes with "infinite renders detected" when we navigate directly to hex Preview
- Offsets are not rendering in 'hex' mode
- Issues are fixed and Preview works correctly
closes #851
=> Web: fix multiple issues of Preview in 'hex' mode

mwdb/web/src/components/RecentView/Views/RecentView.tsx
RecentView component has not initial query passing by props, and after first request query was removed
Now query is not removed after first request
**Test plan**
closes #866
=> add fix passing initial query into RecentView

deploy/docker/Dockerfile, docs/setup-and-configuration.rst, docs/whats-changed.rst, mwdb/core/util.py, requirements.txt
Using ppdeep was really bad idea because Python-based implementation is awfully slow (almost 500x comparing to libfuzzy)
For 40MB file it takes 2 minutes to evaluate a hash:
```
libfuzzy
24576:Nvk8JqACY/kDtsyDULLk9iFySeLMu/lUHGg:SzACj78LkPR1Kmg 0.24330997467041016
ppdeep
24576:Nvk8JqACY/kDtsyDULLk9iFySeLMu/lUHGg:SzACj78LkPR1Kmg 113.24647259712219
```
MWDB uses libfuzzy-dev native dependency like in v2.8.0. It requires native dependency to be installed.
closes #865
=> Rollback from using ppdeep to python-ssdeep (libfuzzy)

mwdb/web/src/commons/helpers/renderTokens.tsx
Searchable elements doesn't work correctly inside some structures like described in https://github.com/CERT-Polska/mwdb-core/issues/863
Fixed issue by ensuring that options are always passed to the next recursion
**Test plan**
closes #863
=> Fix renderTokens: options were not always passed to next recursive call

mwdb/web/src/commons/helpers/renderTokens.tsx, mwdb/web/src/components/RichAttribute/MarkedMustache.tsx
…space
**What is the current/new behaviour?**
Yet another encoding maze:
Markdown doesn't render links that contain space `[name](/q=attr:"my value")`
It means we should use URI-encoding for these links, but React-Router's Link expects non-encoded part URI, so we need to decode it before passing to `Link`
=> Fix: Search links rendered rich attributes break when value contains space

mwdb/paths.py
MWDB Core webapp doesn't work after installation from PyPi (serve_web=1)
Default path to the web fiels was updated.
=> Fix: Update web_bundle_dir after changing build engine to Vite

requirements.txt
Werkzeug >=2.0.0, <3.0.1 has a bug (in some cases, a security bug) that may result in excessive CPU usage and worker timeout when huge file (usually over 50MB) with specific layout is uploaded to MWDB.
The issue is when uploaded file contents are meaningful/random at the beginning (contain CR/LF bytes) and then are extensively padded with zeroes. This is common file pattern for bloated malware samples and memory dumps, so it may highly affect performance or even cause a denial of service if MWDB is flooded with such file uploads.
References:
- https://www.cve.org/CVERecord?id=CVE-2023-46136
- https://github.com/pallets/werkzeug/pull/2801
=> Bump werkzeug to 3.0.1

docs/integration-guide.rst
The template code in the doc does not build with npm. The About component is not imported as it does not exist:
```
import About from "@mwdb-web/components/About";
```
The doc also hid some of the code-blocks due to a missing newline after the placeholder.
Updating the template code to import the AboutView
```
import { AboutView } from "@mwdb-web/components/Views/AboutView";
```
**Test plan**
=> Update integration-guide.rst - update to AboutView from About 

mwdb/app.py, mwdb/core/config.py, mwdb/core/log.py, mwdb/resources/__init__.py, mwdb/resources/auth.py
We're buried in tons of non-meaningful logs without any option to set the verbosity. Non-meaningful logs are:
- information about usage of deprecated endpoints
- 'before_request'/'request' logs which are useful for debugging hanging or slow endpoints, but only for debugging
- threadName, moduleName, lineNo which doesn't carry any useful information that can't be read from the log itself
Missing `request` logs can be easily replaced with metrics introduced by https://github.com/CERT-Polska/mwdb-core/pull/908
- introducing DEBUG level that can be turned on via `enable_debug_log` option in configuration
- setting verbosity level of logs mentioned above to DEBUG
=> Set level of repetable logs to debug

mwdb/app.py, mwdb/core/deprecated.py, mwdb/core/metrics/__init__.py, mwdb/model/api_key.py, mwdb/resources/__init__.py, mwdb/resources/blob.py, mwdb/resources/config.py, mwdb/resources/download.py, mwdb/resources/file.py, mwdb/resources/metakey.py, mwdb/resources/object.py, mwdb/resources/search.py
MWDB Core has few deprecated features that are waiting for removal. To be sure that we won't break anything, we need to monitor usage of these features.
Previously monitoring was done via `logger.warning` but it appeared to be pretty inefficient with current amount of deprecated things. In addition, not all deprecated features have been covered. This PR notifies about deprecated API usage via Prometheus metrics (introduced in https://github.com/CERT-Polska/mwdb-core/pull/908) and debug-level logs.
Another important change is rename from `api_requests` to `mwdb_api_requests`, it's more convenient to have prefixed metric names.
=> Monitor deprecated API usage via Prometheus metrics

mwdb/core/metrics/redis_counter.py
Right now, `/api/varz` returns only a few or none metrics when there are at least two for different gauges.
=> metrics: Fix bug in collecting metrics for /api/varz

mwdb/core/deprecated.py, mwdb/model/api_key.py
Right now it shows only `None` because `g.auth_user` is not yet set.
=> metrics: Indicate which user used legacy_api_key_v2

mwdb/model/user.py, mwdb/schema/comment.py, tests/backend/test_api.py
- Deleting user that is an author of object comment results in ISE 500
- We can delete users with comments and author field for these comments is just set to NULL.
**Test plan**
1. Create user
2. Log in to that user, upload file, comment it
3. Log in back to admin account and try to delete a sample
=> Fix: deleting user that authored some comments

mwdb/core/search/parse_helpers.py
`attribute.virusshare:00005` is queried using the following JSONpath query: `$ ? (@ == \"00005\" || @ == 00005)` while 00005 is not correct number literal.
Fixed regex that recognizes correct numbers and booleans.
=> Fix: Don't treat digits with leading zeroes as correct numbers

mwdb/schema/attribute.py, tests/backend/test_attributes.py
Mentioned in #907, if we try to set `0` value in JSON/object mode, we get ValidationError as value is considered empty
The only empty values are `"", {}, [], null`
**Test plan**
Covered by automated test
=> Fix: Don't treat 0 number as an empty attribute value

mwdb/app.py, mwdb/core/app.py, mwdb/core/rate_limit.py, mwdb/resources/api_key.py, mwdb/resources/attribute.py, mwdb/resources/auth.py, mwdb/resources/blob.py, mwdb/resources/comment.py, mwdb/resources/config.py, mwdb/resources/download.py, mwdb/resources/file.py, mwdb/resources/group.py, mwdb/resources/karton.py, mwdb/resources/metakey.py, mwdb/resources/oauth.py, mwdb/resources/object.py, mwdb/resources/quick_query.py, mwdb/resources/relations.py, mwdb/resources/remotes.py, mwdb/resources/search.py, mwdb/resources/server.py, mwdb/resources/share.py, mwdb/resources/tag.py, mwdb/resources/user.py, requirements.txt
I tried to modify something around limits and feel that Flask-Limiter is not exactly a good fit to our needs. `rate_limited_resource` decorator is awfully hacky and Flask-Limiter doesn't provide a good way to make more dynamic configuration of limits.
In the same time: Flask-Limiter is just a wrapper on [limits library](https://limits.readthedocs.io/en/stable/#). I found we can use it directly and implement rate limiting in `before_request` instead of relying on decorators
**Test plan**
1. Enabled rate limits and set pretty low limit for method and resource
2. Hit the limit and checked if `Rate-Limit` header looks good
=> Use limits directly instead of Flask-Limiter

mwdb/core/karton.py
If MWDB can't load Karton producer on load time, it gives up completely and marks it as unavailable
When Karton is enabled, we try to load it on every request until it succeeds.
**Test plan**
related with #891
=> Fix: Try to load Karton lazily if can't be loaded eagerly

mwdb/web/src/components/AttributesAddModal.tsx, mwdb/web/src/components/ShowObject/common/AttributeRenderer.tsx, mwdb/web/src/components/ShowObject/common/AttributeValue.tsx
- "Object" values should be actually called "JSON" values
- "JSON" value should not be a default, I'm not sure why we're actually switching to JSON every time someone wants to provide a value
- Attribute preview should be rendered always by reusing existing components, not only for Rich attributes. In addition, right now JSON values are not parsed at all and they're passed to preview as strings
Related with #907 
Before change it looks like that:
After change it will look like that:
=> Fix AttributeAddModal to make JSON values less concerning

requirements.txt
psycopg2-binary 2.8.5 is pretty obsolete and wheels are generated only up to Py 3.8
Bumped to psycopg2-binary 2.9.9
=> Bump psycopg2-binary to 2.9.9

mwdb/model/__init__.py, mwdb/model/object.py, mwdb/model/object_permission.py
Just a very small fix for something that always bothered me: two big classes in single module, with the most relevant one somewhere in the middle.
=> Refactor: move ObjectPermission to separate module

mwdb/model/object.py
- When tag is added concurrently: MWDB incorrectly recovers from conflict and re-raises IntegrityError due to incorrect sanity check.
- `db_tag in self.tags` doesn't work when db_tag is transient object and doesn't have primary key which is used for comparison.
`Object.add_tag` correctly returns False in case of IntegrityError indicating that tag was already added (by concurrent transaction).
=> Fix: ISE 500 on concurrent tag addition

deploy/docker/Dockerfile-web, deploy/docker/Dockerfile-web-dev, docker/nginx.conf.template, docker/start-web.sh, docs/setup-and-configuration.rst
- ~~[ ] I've added automated tests for my change (if applicable, optional)~~
- we can't easily set client_max_body_size without building own image
- `nginx` Docker image provides correct `start-web.sh` on its own which is then unnecessarily overridden by our Dockerfile
- Added `NGINX_MAX_UPLOAD_SIZE` env reference to `client_max_body_size` option in `nginx.conf.template`
- Set correct path for `nginx.conf.template` (`/etc/nginx/templates/default.conf.template` instead of `/etc/nginx/conf.d/default.conf.template`) and added default `50M` in `ENV` directive.
**Test plan**
- Check if setting works with no env value set and with custom value (I've done it during manual test of my …
=> Allow to set custom upload size limit via NGINX_MAX_UPLOAD_SIZE env var in mwdb-web Docker image

mwdb/core/service.py
Change introduced in https://github.com/CERT-Polska/mwdb-core/pull/916 was calling `jsonify` on all view method results that were not Response objects.
It was found that plugins are using other response formats accepted by Flask e.g. `{"data": ...}, 200` which were incorrectly jsonified into array `[{"data": ...}, 200]` instead being treated as `<payload>, <status_code>)` structure
Responses from view methods are directly passed to the Flask. The only exception is `None` that is returned as jsonified `null` (Flask explicitly rejects None with exception "TypeError: The view function for '...' did not return a valid response. The function either returned None or ended without a return …
=> Fix: don't jsonify view method result in Resource

mwdb/core/karton.py
Passing tags to karton can be extremly useful in some scenarios.
When a Task object is created for karton, currently only attributes and a Resource object are passed.
In addition tags will now be passed (as strings) to enable conditional processing by karton based on file tags.
**Test plan**
From within karton modules you should be able to access file tags by ```task.get_payload("tags")```.
=> Passing tags to karton.

mwdb/web/src/components/RecentView/Views/RecentView.tsx
When "Diff with.." option is used, MWDB UI escapes from diff mode into standard mode when we use Search. It happens because setSearchParams forget about `diff=` argument in query parameters.
Fixed setSearchParams invocation to not lose other arguments while updating search params
**Test plan**
=> Fix: don't forget diff= parameter while searching in diff mode

mwdb/schema/config.py, mwdb/schema/file.py
`latest_config` field returned by `/api/file/<hash>` endpoint returns all fields for config item including relationships and attributes. This makes file response unnecessarily large, especially when config has lots of relationships to other objects.
`latest_config` field returns limited information, similar to ConfigListItemResponseSchema but including configuration contents.
**Test plan**
=> Fix: Too eager schema for FileItemResponseSchema.latest_config field

mwdb/core/search/fields.py, mwdb/core/search/parse_helpers.py
JSONB wildcard queries are very slow because there is no supported JSONB "LIKE" operator that works with current implementation of GIN index. In the same time, LIKE on `jsonb_path_query` function result is very expensive.
So queries like:
```
cfg:"*/content/*"
```
may take minutes, especially when matching rows are really far in config table, which is far more than usual request timeout setting.
Configs are too long to be indexed by simple btree, but we found that simple `object.cfg::text LIKE "%...%"` works much faster even if it performs a full table scan. It's not exactly what we want if we use key predicate (`cfg.urls:*/content/*`) so it's still combined with the original …
=> Fix: faster wildcard queries for JSONB fields

mwdb/model/object.py, mwdb/model/user.py
Followers are joined for every Object instance and Favorites are joined for every User instance. It's completely unnecessary and has negative impact on query performance.
Joined relationships in objects should be used only for fields included in listing schemas like `ObjectListItemResponseSchema` to avoid N+1 problem.
Favorites/Followers are loaded lazily.
=> Fix: don't use joined relationship for 'favorite' parameter

mwdb/core/search/fields.py, mwdb/core/search/parse_helpers.py
JSON search code is pretty complicated because it assumes that wildcard search that is not a full-text search (with wildcards on both sides `*value*`) can also search for nested objects, so it needs to look for two possible combinations of escaping: 
- quoted values `{"key": {"current_dir": "C:\\Windows"}}` so `cfg.key:*C:\\Windows*` needs to search for `LIKE '%C:\\\\Windows'` as the value returned by `json_path_query(cfg, '$.key') #>> '{}'` is `{"current_dir": "C:\\Windows"}`
- unquoted values `{"key": "C:\Windows"}` so `cfg.key:"C:\\Windows*"`  needs to search for `LIKE "C:\\Windows%"` as the value returned by `json_path_query(cfg, '$.key') #>> '{}'` is `C:\Windows`
We just assume …
=> Simplify wildcard JSON searching

mwdb/web/src/components/RecentView/Views/RecentView.tsx, mwdb/web/src/components/RecentView/Views/RecentViewList.tsx
When user submits a query, the first page of results is actually fetched twice in non-counting mode:
1. First time the list goes blurred and frontend sends a query for first 10 results
2. If there's no error, query is submitted into URI and frontend starts dynamic fetch of all results, including first page.
It makes the search slower, although not twice as slow because some data are already cached by database, so usually the second run is a bit faster.
- Query is submitted as soon as user presses Enter, without "blurry" state
- Counting is done in parallel.
In the same time, I fixed some glitches that I found during testing.
=> Simplified RecentView without preloading

mwdb/web/src/App.tsx, mwdb/web/src/components/VersionMismatchWarning.tsx
When MWDB Core is updated, users usually still have cached older version of a client which may lead to glitches and errors.
Added warning that recommends to force reload webpage using CTRL+F5 when version mismatch is detected.
=> Frontend: add warning banner when server version is different than client version

mwdb/core/search/parse_helpers.py, tests/backend/test_attributes.py
When we try to use non-numerical value in range search, query fails with Internal server error because of incorrectly formatted jsonpath.
When value doesn't look like a number or known JSON literal, value is properly quoted and escaped before put in the jsonpath query.
**Test plan**
Added automated test to fulfill use-case mentioned in related issue
closes #952
=> Fix: ISE 500 when non-numerical value appears in range search in JSON column

docker-compose.yml, docs/conf.py, docs/whats-changed.rst, mwdb/version.py, mwdb/web/package-lock.json, mwdb/web/package.json, setup.py
This release is focused on further improvements of search performance and bugfixes.
It's recommended to upgrade your karton-system to v5.4.0 before applying this upgrade.
**New features and improvements:**
* Improved performance of object lists in Web UI (https://github.com/CERT-Polska/mwdb-core/pull/949)
* Improved performance of wildcard queries for JSONB fields by @psrok1 in https://github.com/CERT-Polska/mwdb-core/pull/943
* Karton is upgraded to v5.4.0 with much faster analysis status lookup method  (https://github.com/CERT-Polska/mwdb-core/pull/938)
* Tags are passed to Karton tasks (by @aBUDmdBQ in https://github.com/CERT-Polska/mwdb-core/pull/934)
* Frontend: added warning banner when server version is different than client version, so user needs to clear cache …
=> Bump version: v2.13.0

mwdb/model/blob.py, mwdb/model/config.py, mwdb/model/file.py, mwdb/model/migrations/versions/6fc42e070495_set_collation_of_fields_that_may_be_.py, mwdb/model/tag.py
I found in documentation that PostgreSQL B-tree index doesn't work by default for left-anchored LIKE queries for columns that doesn't have 'C' collation set.
```
The optimizer can also use a B-tree index for queries involving the pattern matching operators LIKE and ~ if the pattern is a constant and is anchored to the beginning of the string — for example, col LIKE 'foo%' or col ~ '^foo', but not col LIKE '%bar'. However, if your database does not use the C locale you will need to create the index with a special operator class to support indexing of pattern-matching queries; see [Section 11.10](https://www.postgresql.org/docs/current/indexes-opclass.html) below. It is also possible to use B-tree indexes for ILIKE …
```
=> Set collation of some string fields to 'C'

mwdb/resources/tag.py, mwdb/schema/tag.py, mwdb/web/src/commons/api/index.tsx, mwdb/web/src/components/ShowObject/common/TagForm.tsx
TagListResource returns all tags matching provided prefix without any limitation. It's especially expensive when we provide a very common prefix e.g. "feed:" or "ripped:"
- Added `count` argument to the endpoint
- `count` is set by default to 20 in "Add tag" autocompletion list
=> Allow to set limit of tags returned by TagListResource

.github/workflows/build.yml
- `docker-compose` (Compose v1) is no longer available on Github Actions
- It's good time to bump other Docker actions as well
=> CI: Bump docker gh actions, use Compose v2

mwdb/cli/web.py
=> Fix: 'mwdb-core configure web' command after transition to Vite

mwdb/core/oauth.py, mwdb/model/oauth.py, mwdb/resources/oauth.py
**Description of changes**
I don't really like the documentation of authlib and the current design of mixins. That's why I think it's a bit unsafe to mix with OAuth2Session and it's much better to make a wrapper that will be exposed via `OpenIDProvider.get_oidc_client` method.
Additional thing is that in future PRs we need to make a series of calls to the provider using fetched access token, we can't do that with current `_get_client` method that creates `OpenIDSession` object internally and disposes it right after the call.
The third thing is that we need to strip `OpenIDClient` methods from unused code paths, copied from `OpenIDMixin`.
**Test plan**
Right now it needs to be tested manually using `docker-compose-oidc-dev`
=> OIDC: Refactor to expose OIDC client object

mwdb/core/oauth/client.py, mwdb/core/oauth/provider.py, mwdb/core/plugins.py, mwdb/model/__init__.py, mwdb/model/oauth.py, mwdb/resources/oauth.py
This PR addresses #965. Depending on the OpenID Provider, usually provider offers additional resources that may tell us more about the specific user, but these resources are non-standard and specific for the provider. We may want to have a dedicated handler for these specific providers
- Additional layer between `mwdb.model.oauth.OpenIDProvider` (now called `OpenIDProviderSettings`) and `mwdb.core.oauth.OpenIDClient` - `mwdb.core.oauth.provider.OpenIDProvider` that implements user and group creation and can be used to create own customized OpenIDProvider classes
- Specialized provider class can be registered by plugin using `PluginAppContext.register_openid_provider_class` method …
=> OIDC: Plugin-customizable OpenIDProvider class

mwdb/resources/oauth.py
Right now, user can't bind existing account to the provider
=> OIDC: Fix small regression after #982

docker-compose.yml, docs/conf.py, docs/whats-changed.rst, mwdb/version.py, mwdb/web/package-lock.json, mwdb/web/package.json, setup.py
New features and improvements:
* Performance improvements:
* Set collation of some string fields to 'C' to better utilize btree index. **Be aware that database migration may took a while** (https://github.com/CERT-Polska/mwdb-core/pull/959)
* Add index on comment.object_id column (https://github.com/CERT-Polska/mwdb-core/pull/988)
* Open-ID Connect improvements:
* Fetching userinfo claims from userinfo endpoint, previously we assumed that they'll be send along with ID Token (https://github.com/CERT-Polska/mwdb-core/pull/972)
* Plugin-customizable OpenIDProvider class (https://github.com/CERT-Polska/mwdb-core/pull/982)
* OpenID Provider group is no longer a workspace and doesn't imply sharing objects within group (https://github.com/CERT-Polska/mwdb-core/pull/974)
* Custom rate limit …
=> Bump version: v2.14.0

mwdb/model/object.py, mwdb/schema/object.py, mwdb/schema/relations.py
- ~~[ ] I've added automated tests for my change (if applicable, optional)~~ (already covered)
- ~~[ ] I've updated documentation to reflect my change (if applicable)~~ (no changes)
There is definitely too much magic there that is quite ineffective. When object has lots of parents, every `Object.access()` that is called in almost every object endpoint will eagerly load all parents and all its tags even if they're not used by the endpoint.
Replaced eager loading with property `accessible_parents` that makes a query when requested. It is then called by proper schema fields.
Other functions that are relying on user's view of parents are already using dedicated query instead of …
=> Don't load filtered-out parents eagerly on every Object.access

mwdb/core/deprecated.py, mwdb/resources/object.py, mwdb/schema/object.py
'page' parameter is deprecated since the initial v2 release, but was used by some mwdb.cert.pl users. Right now it's not even documented in the current API.
This PR removes 'page' parameter support in v3.0.x branch.
=> v3: Drop support for legacy 'page' parameter

docs/user-guide/9-Sharing-objects.rst, mwdb/core/capabilities.py, mwdb/core/deprecated.py, mwdb/model/object.py, mwdb/web/src/commons/auth/capabilities.tsx, mwdb/web/src/types/types.ts, tests/backend/test_permissions.py
`share_queried_objects` was a very obscure feature that allow certain users to access any sample in the system if they know a direct link to the specific object. It was never used in mwdb.cert.pl and is not very well supported e.g. you can't reach these sample via search by providing a hash.
This PR removes support for share_queried_objects capability.
Also removed `DeprecatedFeature` that I forgot to remove in #1003
=> Drop: share_queried_objects capability

mwdb/model/migrations/versions/465b589d0362_remove_share_queried_objects_from_groups.py
Migration that removes "share_queried_objects" capability from existing groups.
=> Remove unsupported 'share_queried_objects' capability from groups

mwdb/core/config.py, mwdb/core/deprecated.py
We're going to remove stale and deprecated features in next major version (v3.0.0). We're already tracking the usage of deprecated API elements but to ensure that we're ready to deploy breaking changes, we're going to temporarily "brownout" old features to check the effects.
This PR introduces `enable_brownout` flag. When enabled, deprecated API elements will throw HTTP 400 (Bad Request) with proper message. The exception is `legacy_api_key_v2` - we're not ready to drop it yet.
=> Feature: brownout deprecated API features via enable_brownout flag

mwdb/model/object.py, mwdb/model/user.py, requirements.txt
I'm missing some features in 1.3.x branch. The 1.3.x branch is also from 2021 and it's good time to switch to something with better support.
This PR upgrades sqlalchemy to 1.4 and all related dependencies to newer versions. Flask-SQLAlchemy is pinned on 3.0.5, because 3.1.0 requires sqlalchemy 2.0. I think this needs a bit more work.
=> Bump sqlalchemy to 1.4 and database-related dependencies

deploy/docker/Dockerfile, deploy/docker/Dockerfile-web, deploy/docker/Dockerfile-web-dev, deploy/docker/Dockerfile-web-unit-test, requirements.txt, tests/backend/Dockerfile
Current base images for Docker are pretty obsolete.
- Bumped Python base image from 3.8 to 3.12
- Bumped Node.js base image from 16.x to 22.x
- Bumped bcrypt to 4.2.1 due to compatiblity problems with newer versions of Python
=> Bump base of Docker images and bcrypt

mwdb/schema/group.py, mwdb/schema/share.py, mwdb/schema/user.py, mwdb/web/src/components/Settings/Views/GroupCreateView.tsx, mwdb/web/src/components/Settings/Views/GroupDetailsView.tsx, mwdb/web/src/components/Settings/Views/UserCreateView.tsx, mwdb/web/src/components/Views/UserRegisterView.tsx
I noticed this problem during integration with OIDC SSO where dots were used in preferred usernames. We don't have any good reason to ban this character.
Dots are allowed in user and group names.
=> Allow dots in user and group names

mwdb/resources/metrics.py, requirements.txt
- `/api/varz` offers Prometheus metrics but sends them with generic `application/octet-stream` Content Type.
- Because of that, there are issues with compatibility with Prometheus v3 which is more strict concerning the Content-Type and doesn't automatically fallback to legacy protocol unless it's configured to do so (https://prometheus.io/docs/prometheus/latest/migration/). 
- Set correct Content-Type for the response (got from `prometheus_client.CONTENT_TYPE_LATEST`)
- Bumped `prometheus-client` to latest. I initially thought that 0.20.0 updates the PrometheusText version to 1.0.0, but misread the changelog and the bump was for OpenMetricsText, so the format we're using stays on …
=> Fix Prometheus metrics MIME type and bump prometheus-client to 0.21.1

mwdb/core/config.py, mwdb/model/file.py
We found that `hash_pathing` is useful also for some object storage solutions like MinIO.
MinIO maps `/` prefixes into actual directories on the file system. Even if we use recommended file system that allows to store lots of files in single directory, various operations using object listing (including internal ones like MinIO scanner) are significantly slowed down.
Unfortunately we can't smoothly migrate to the new naming scheme without fallback.
- Add `hash_pathing_fallback` option. When `File.open()` fails to open file using current `hash_pathing` setting, it tries to use opposite one. It works only for gathering file contents, all new files will be stored using the chosen scheme …
=> Add 'hash_pathing_fallback' option, remove File.get_path() method

docs/setup-and-configuration.rst, mwdb/core/config.py
This option should be enabled only if needed.
=> Fix: disable hash_pathing_fallback by default

mwdb/model/object.py, mwdb/resources/relations.py, mwdb/schema/object.py, mwdb/schema/relations.py, mwdb/web/src/commons/helpers/index.ts, mwdb/web/src/components/ShowObject/common/RelationBox.tsx, mwdb/web/src/components/ShowObject/common/TypedRelationsBox.tsx
This PR addresses the same problem as #881 and #1008.
If there are more relationships than 100 within a specific type, only the latest 100 are shown via API. Limiting must be done typewise because MWDB UI divides relationships into object types:
So there is a possibililty that with 100+ parent samples, blob relationship won't be shown which is surprising and incorrect behavior.
If there is 100 or more relationships within a specific type, MWDB shows additional link to query that allows to search for all related objects of that type.
Usually the relationships within type are in specific direction, that's why MWDB UI tries to deduce whether "parent query" or "child query" should be …
=> Limit exposed relationships type-wise to 100 elements

mwdb/web/src/components/RichAttribute/MarkedMustache.tsx
When multiple value lookups are done within the same context, some of them may not reset the lastPath value.
So the following template with searchable `value.category`
```
{{#if}}{{value.id}}{{/if}}
{{#then}}
{{@value.category}}
{{/then}}
```
creates search link to `attribute.test-attribute.id.value.category:"<category value>"` instead of `attribute.test-attribute.category:"<category value>"`
Value of lastPath is reset back to parentPath on every lookup in MustacheContext.
=> Fix: reset MustacheContext.lastPath before lookup

mwdb/web/src/styles/index.css
Tags overlap in relations graph, described in #1049
**Test plan**
Got this after a heated conversation with chatgpt so it needs to be tested in many scenarios, compared to existing results, etc. If i'll have time, i'll try to add this change to a staging environment of MWDB with "real" samples
closes #1049
=> (Try to) fix CSS for relations graph tags

mwdb/web/src/commons/ui/ConfirmationModal.tsx
In a commit a while ago, the following CSS property was added by default to the `ConfirmationModal` component: `maxHeight: "80%"`.
We have many plugins that use this component and as a result many of our plugins were broken in the way they are displayed.
Add the ability to use custom styles that can override the existing ones.
**Test plan**
I tested this code to see that just adding it doesn't break anything, and then tested to see if this allows me to fix the issue - it does, by allowing me to override the default styles
=> Feat: Add ability to add custom content style to ConfirmationModal

docs/rich-attributes-guide.rst, mwdb/web/src/components/RichAttribute/MarkedMustache.tsx
Sometimes it's useful to have an information about position of element in the array.
For example: when we enumerate values and want to put comma in between, we may do that by rendering leading comma for all values except the first. Right now it's impossible to do that in Rich attributes.
For array enumeration, two additional variables are injected into context:
- `$arrayIndex` set to the index of current element
- `$isLastElement` that is set to `true` when current element is last in the array and `false` otherwise
These variables are available only directly in the array section and are not available in nested sections.
Using these values, we're able to conditionally render a comma …
=> Rich attributes: put arrayIndex and isLastElement local variables in array sections
