CERT-Polska/mwdb-core

core/service.py
=> Fix typo: occured -> occurred

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, INSTALL.md
Adds issue and pull request templates (mostly copied from mquery, with minor changes).
=> Issue and pull request templates

core/service.py, requirements.txt, resources/api_key.py, resources/auth.py, resources/blob.py, resources/comment.py, resources/config.py, resources/download.py, resources/file.py, resources/group.py, resources/metakey.py, resources/object.py, resources/relations.py, resources/search.py, resources/server.py, resources/share.py, resources/tag.py, resources/user.py
- API documentation is inconsistent, contains few errors and has undocumented methods that should be documented
- Bumped apispec to latest to fix some issues (e.g. https://github.com/marshmallow-code/apispec/issues/209)
- API documentation with much better coverage, accessible via `/docs` web endpoint.
**Test plan**
- Go to the `/docs` and check the completion and readability.
- Expand all the endpoints in Swagger to test for errors (components are lazy-loaded)
- Check "try it out" functionality
=> Complete API documentation

malwarefront/src/components/AttributeUpdate.js
Information about submitting changes to attributes. 
closes #38
=> Add attribute update message

core/search/fields.py
**Test plan**
Search for uploads from other user.
closes #14
=> Add capability for user to search for group uploads

model/object.py
- Handle IntegrityError in nested transaction when the same relationship was added concurrently by another transaction
- Permission inheritance should be done in the same transaction
**Test plan**
- On master, send two concurrent `/object/{parent}/child/{child}` requests for two unrelated objects. Second request should fail with 500/502 due to unhandled IntegrityError
- After switching to branch: both requests should return 200
```
mwdb_1          | 172.22.0.6 - - [30/Jun/2020:17:49:36 +0000] "PUT /file/146d1b7e085c4eb694ebeb6506911303f6984c9d8117c10c88a50b36c780e26a/child/3be031d181d7c1d6d2bde5cc81ab0b7407dfb0e75a6c6de667678a578014c59d HTTP/1.1" 200 5 "http://127.0.0.1/docs" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 …
```
=> Fixed race condition in Object.add_parent

resources/__init__.py, resources/relations.py, resources/search.py
- Malwarecage shows deprecation warning in logs if somebody used deprecated endpoint. It will be really helpful for determining if it's already safe to remove deprecated features from API.
=> Show deprecation warning when deprecated endpoint has been used

core/schema.py, resources/server.py, schema/server.py
**What changed?**
- Moved the `server` endpoints schema to `schema/` following the convention
- Improved documentation a bit
**Test plan**
- Check if endpoints look and work ok in http://127.0.0.1/docs
=> Revisited server endpoints

core/schema.py, resources/search.py, schema/search.py
**What's changed?**
- Adapted search to new convention
**Test plan**
- Check if search still works
=> Revisited search endpoints

schema/metakey.py
- Missing url field in `MetakeyItemResponseSchema` causes lack of clickable attribute value
- Added url field to `MetakeyItemResponseSchema`
=> Fix missing attribute URL

malwarecage/core/capabilities.py, malwarecage/model/object.py, malwarecage/resources/object.py, malwarecage/web/src/App.js, malwarecage/web/src/commons/api/api.js, malwarecage/web/src/commons/ui/RefString.js, malwarecage/web/src/components/Capabilities.js, malwarecage/web/src/components/ShowConfig.js, malwarecage/web/src/components/ShowObjectPresenter.js, malwarecage/web/src/components/ShowSample.js, malwarecage/web/src/components/ShowTextBlob.js
Ability to remove object from web UI, functionality available only to admins with permissions to delete objects
**Test plan**
TODO
closes #121
=> Delete object feature

tests/backend/test_permissions.py, tests/backend/utils.py
tests for removing objects functionality
closes #130
=> Test removing objects

malwarecage/web/src/components/Navigation.js, malwarecage/web/src/styles/index.css, tests/frontend/cypress/integration/blob.js, tests/frontend/cypress/integration/config.js, tests/frontend/cypress/integration/sample.js
Recent word is present in the navigation menu.
Recent word is not present in the navigation menu and font awesome icons were added.
**Test plan**
Login to Malwarecage and check if changes are present.
closes #140
=> Removed Recent word from menu and added font awesome icons

malwarecage/resources/blob.py, malwarecage/resources/config.py, malwarecage/resources/file.py, malwarecage/resources/object.py
file, config and blob methods are in the wrong place in the documentation
fix the documentation by adding appropriate dedicated methods for the mentioned types of objects
closes #147
=> Fix docs for delete method

mwdb/web/src/components/ShowSample.js, tests/frontend/cypress/integration/sample.js
There is a lacking space in File name attribute in sample details view.
Space is added.
**Test plan**
Check sample details view.
closes #133
=> Space added

mwdb/resources/__init__.py, mwdb/resources/api_key.py
Information about capabilities is missing after the Forbidden error.
Detailed messages after Forbidden error are present when capability is missing.
**Test plan**
Run frontend blob.js using normal user when adding text blob capability is missing.
closes #47
=> Details of capability added to Forbidden error messages

LICENSE, LICENSE.AGPL, README.md
=> Add license (AGPLv3 with exceptions for plugins)

mwdb/version.py, mwdb/web/package-lock.json, mwdb/web/package.json, mwdb/web/src/commons/package.json, setup.py
Next development release after rebranding from `malwarecage` to `mwdb-core`.
- Renamed frontend "commons" module from `@malwarefront/*` to `@mwdb-web/commons/*`. All common modules are moved to the single `@mwdb-web/commons` package.
- Removed 'humanhash' attribute from files
- Migrated to marshmallow v3, mwdb-core returns HTTP 400 in case of invalid JSON instead of 500
- Modernized Search view to provide the same functionality as `Recent object` views, but for all types of objects.
- Minor UI fixes
=> Bump version: 2.0.0-alpha3

mwdb/model/object.py, tests/backend/test_relations.py
=> Fix: wrong share order for uploaded objects with parent

mwdb/web/src/components/ShowObjectPresenter.js, mwdb/web/src/styles/index.css
=> Recovered detailed view header and prettified icons a bit

mwdb/web/config-overrides.js
- Web plugins are not discovered by loader
- Fixed web plugin discovery
=> Fix: web plugin discovery regression

mwdb/web/src/components/UserProfile.js
Wrong profile view layout in browsers different than firefox
Fix this problem using bootstrap d-flex class and apply it in profile table
closes #207
=> Fix profile view layout

mwdb/web/src/components/UserRegister.js
Submit button is still active after successfully registration
Submit button is deactive after successfully registration
closes #195
=> More visible success of registration

mwdb/core/plugins.py
- Plugin information is broken
- Plugin information shows correctly in `About`
=> Fixed plugin information in About

mwdb/web/src/commons/ui/ConfirmationModal.js, mwdb/web/src/components/ShowObjectPresenter.js
Delete modal is closed just after request, and object still exist
Delete modal is waiting for API response to be closed
**Test plan**
Delete some object
closes #219
=> Fix object delete modal response

README.md, mwdb/version.py, mwdb/web/package-lock.json, mwdb/web/package.json, mwdb/web/src/commons/package.json, setup.py
Version bump for mwdb-core 2.0.0 :tada:
=> Release version: 2.0.0

docs/setup-and-configuration.rst
=> docs: fix typo

docs/user-guide/7-Lucene-search.rst, mwdb/core/search/fields.py, mwdb/model/config.py, mwdb/model/migrations/versions/f5602d538e9c_.py, mwdb/model/migrations/versions/f5602d538e9c_use_jsonb_for_configurations.py, tests/backend/test_search.py
change cfg column in config model from JSON to JSONB
support array search for JSON fields by using jsonb_path_query
**Test plan**
Query some JSON fields, it is possible that automatic tests will be added to this PR
=> Array search fo JSON fields

docs/conf.py, docs/setup-and-configuration.rst, mwdb/core/config.py, mwdb/model/file.py, mwdb/templates/mwdb.ini.tmpl, mwdb/version.py, mwdb/web/package-lock.json, mwdb/web/package.json, mwdb/web/src/commons/package.json
- Blob storage feature is not included in documentation.
- There is ambiguity between blob as object type and blob as storage type.
- Feature is renamed to "S3-compatible storage support"
- S3-compatible storage feature is included in documentation.
=> Documentation for S3-compatible storage support and small code refactor.

mwdb/web/src/commons/context/index.js, mwdb/web/src/components/ShowConfig.js, mwdb/web/src/components/ShowObjectPresenter.js, mwdb/web/src/components/ShowSample.js, mwdb/web/src/components/ShowTextBlob.js
- React doesn't really like nested dicts and methods in component state
- GlobalContext update is simplified
=> Simplified object views' GlobalContext

mwdb/schema/object.py, mwdb/web/src/commons/api/index.js, mwdb/web/src/components/RecentView/RecentView.js
Display how many objects has been found during search
closes #246
=> Count objects in frontend during search

mwdb/web/package-lock.json, mwdb/web/package.json
Added missing package to package-lock.json
=> Missing @fortawesome/free-regular-svg-icons in package-lock.json

mwdb/app.py, mwdb/resources/remotes.py
=> Remote API: Endpoint for arbitrary API requests

mwdb/resources/server.py, mwdb/schema/server.py, mwdb/web/src/commons/api/index.js, mwdb/web/src/components/ShowConfig.js, mwdb/web/src/components/ShowObject/PushAction.js, mwdb/web/src/components/ShowObject/index.js, mwdb/web/src/components/ShowSample.js, mwdb/web/src/components/ShowTextBlob.js
Added the ability to push an object onto a remote instance from the object view in UI
**Test plan**
Checking if the object is being transferred
partial #157
=> Remote API: Push object remote in UI

mwdb/web/src/components/ShowConfig.js, mwdb/web/src/components/ShowSample.js, mwdb/web/src/components/ShowTextBlob.js
In Preview tab there is less action icons than in Details
Same set of action buttons in Preview and Details tab
**Test plan**
Check object action buttons
closes #264
=> Same set of buttons in Preview and Details tab

CONTRIBUTING.md
=> CONTRIBUTING.md: Prettify => Prettier

mwdb/web/src/components/Attributes.js, mwdb/web/src/components/ShowObject/Views/AttributesBox.js
ObjectAttributes as class component
ObjectAttributes as functional component
**Test plan**
Check if everythings work fine
=> Refactor: ObjectAttributes component

mwdb/web/src/App.js, mwdb/web/src/components/UserLogin.js
- If user navigates to non-existent page, page is blank
- If user previous navigation was '/login', it is redirected back to '/login' even if was successfully logged in
- Added default route that redirects back to '/'
- '/login' redirects to '/' if user is already logged in
- Changed 'routes' interface for plugins. If extra routes are wrapped by additional component, `<Switch>` doesn't work correctly. They must be direct children of `Switch` component to work properly.
=> Redirect to '/' for nonexistent or unreachable routes

deploy/docker/Dockerfile-web, deploy/docker/Dockerfile-web-dev, mwdb/web/package-lock.json, mwdb/web/package.json
- Dependabot tries to bump Madge but it doesn't work because Node.js version is too old (#305)
- Bumped Madge to 4.0.2 and set Node version to 14.x from 8.x.
=> Bump madge to '4.0.2'

mwdb/web/src/components/ShowConfig.js
Fixed missing pull button in "Details" tab of Config remote view.
=> Remote: fixed missing pull button

docs/conf.py, mwdb/version.py, mwdb/web/package-lock.json, mwdb/web/package.json, mwdb/web/src/commons/package.json, setup.py
=> Version bump: 2.2.0

docs/conf.py, mwdb/version.py, mwdb/web/package-lock.json, mwdb/web/package.json, mwdb/web/src/commons/package.json, mwdb/web/src/components/ShowObject/Views/CommentBox.js, setup.py
Due to missing `useCallback` dependency, comments arer not reloaded after navigating to the parent/child object.
Comments are reloading correctly
=> Fix: comments are not reloaded after navigation to the parent/child object

mwdb/web/src/commons/remotes/index.js, mwdb/web/src/commons/ui/ObjectLink.js, mwdb/web/src/commons/ui/RefString.js, mwdb/web/src/components/ConfigStats.js, mwdb/web/src/components/ConfigTable.js, mwdb/web/src/components/DagreD3Plot.js, mwdb/web/src/components/Navigation.js, mwdb/web/src/components/RecentBlobs.js, mwdb/web/src/components/ShowObject/Views/LatestConfigTab.js, mwdb/web/src/components/ShowObject/Views/SharesBox.js, mwdb/web/src/components/ShowSample.js, mwdb/web/src/components/ShowTextBlob.js
I've encountered broken links on global stats page. Basically, the URL looked like `//search` and thus the browser 
didn't consider it as relative URL.
While looking at the code, I've noticed some inconsistencies when creating `remotePath` and extracted the logic into a
new hook - `useRemotePath`.
Although I'm not sure if it's the correct way to use hooks.
Maybe it should be `const remotePath = makeRemotePath(useRemote())`?
**Test plan**
Clicking the links, I guess.
However, I didn't test with added remotes.
=> web: Extract useRemotePath

mwdb/web/src/commons/helpers/search.js, mwdb/web/src/commons/ui/RefString.js, mwdb/web/src/components/ConfigStats.js, mwdb/web/src/components/ConfigTable.js, mwdb/web/src/components/DagreD3Plot.js, mwdb/web/src/components/Navigation.js, mwdb/web/src/components/RecentBlobs.js, mwdb/web/src/components/RelationsPlot.js, mwdb/web/src/components/ShowObject/Views/LatestConfigTab.js, mwdb/web/src/components/ShowObject/Views/SharesBox.js, mwdb/web/src/components/ShowSample.js, mwdb/web/src/components/ShowTextBlob.js
**What is fixed?**
- Unified paths that include remotePath, fixed partially by #323.
=> Web: Unified remotePath

tests/backend/test_attributes.py, tests/backend/utils.py
Automated tests for removing attributes definition
=> Tests: remove attribute definition

mwdb/web/src/commons/api/index.js, mwdb/web/src/components/AttributeUpdate.js
Button inside AttributeUpdate view that open modal for removing attribute definition
**Test plan**
Remove some attribute definition and check if its gone
=> Remove defined attribute from UI

mwdb/web/src/commons/api/index.js, mwdb/web/src/components/ShowObject/Views/RelationsBox.js
Allow to remove relationship between objects from web UI.
**Test plan**
Check that if the relationship between the objects has disappeared along with inherited permissions
=> UI: Support removal of relationships

tests/backend/relations.py, tests/backend/test_relations.py, tests/backend/utils.py
Test of removal of various relationships with checking of object permissions for many users.
closes #265
=> Backend tests for relation removing

mwdb/web/src/commons/ui/RefString.js, mwdb/web/src/components/ShowObject/Views/CommentBox.js
null for comment author and share related user if the user was deleted
the mentioned things have been replaced by (deleted)
**Test plan**
Delete some users with uploaded files by then recently and check if everything work fine
closes #350
=> Handle null deleted user login in web UI

mwdb/web/src/App.js, mwdb/web/src/components/Navigation.js, mwdb/web/src/components/Settings/SettingsView.js, mwdb/web/src/components/Settings/Views/AttributeDefine.js, mwdb/web/src/components/Settings/Views/AttributeUpdate.js, mwdb/web/src/components/Settings/Views/GroupRegister.js, mwdb/web/src/components/Settings/Views/GroupUpdate.js, mwdb/web/src/components/Settings/Views/ManageAttributes.js, mwdb/web/src/components/Settings/Views/ShowGroups.js, mwdb/web/src/components/Settings/Views/ShowPendingUsers.js, mwdb/web/src/components/Settings/Views/ShowUsers.js, mwdb/web/src/components/Settings/Views/UserCreate.js, mwdb/web/src/components/Settings/Views/UserUpdate.js
Administrative views with you can acces by dropdown from navigation bar.
Administrative view where you can navigate more easily and switch between views for managing users, groups and attributes.
**Test plan**
Check all administrative views
=> New administrative views navigation

mwdb/web/package-lock.json, mwdb/web/package.json, mwdb/web/src/commons/package.json, mwdb/web/src/commons/ui/Autocomplete.js, mwdb/web/src/commons/ui/MemberList.js, mwdb/web/src/commons/ui/index.js, mwdb/web/src/components/AttributeUpdate.js, mwdb/web/src/components/Settings/Views/AttributeUpdate.js, mwdb/web/src/components/ShowObject/Views/SharesBox.js, mwdb/web/src/components/ShowObject/Views/TagBox.js, mwdb/web/src/components/Upload.js, mwdb/web/src/components/UserLogin.js
Web UI uses `react-autocomplete` which has known issues. This project is abandoned, so it won't be developed anymore
We can build our own "autocomplete" component based on simple Bootstrap dropdown. It works much better than the previous implementation.
React Dropdown also properly handles component focus, dropdown position and keyboard events. So it fixes one of the most ancient issues with `react-autocomplete`.
**Test plan**
Check if modified components still work properly
closes #8
=> UI: Replaced react-autocomplete with custom based on Bootstrap dropdown

mwdb/web/src/App.js, mwdb/web/src/commons/ui/GroupBadge.js, mwdb/web/src/components/Profile/ProfileView.js, mwdb/web/src/components/Profile/ProfileViews.js, mwdb/web/src/components/Profile/Views/ProfileAPIKeys.js, mwdb/web/src/components/Profile/Views/ProfileCapabilities.js, mwdb/web/src/components/Profile/Views/ProfileDetails.js, mwdb/web/src/components/Profile/Views/ProfileGroups.js
- Navbar in Profile to improve the navigation and make it look similar to the Settings view
- Added icons to GroupBadge
- Added separate view for Profile/Groups with friendly descriptions
=> UI: Profile view improvements

mwdb/web/src/components/Profile/ProfileView.js, mwdb/web/src/components/Settings/SettingsView.js, mwdb/web/src/styles/index.css
- Sidenav in Profile and Settings view doesn't look well in narrow window (e.g. mobile)
- There is no active element indication
=> UI: Responsive sidenav with active item indicator

mwdb/web/src/components/Settings/Views/AttributeDetails.js
Hide attribute permissions section in UI if user doesn't have managing_users capability.
**Test plan**
Check if users with specific capabilities have access to attributes permissions component.
=> UI: Hide attributes permissions for non admin users

mwdb/model/migrations/versions/4f0405411201_migrate_karton_attribute.py
- Migrates `karton` attributes from old mwdb-karton-plugin into new KartonAnalysis objects
**Test plan**
:heavy_check_mark: Checked on production-alike data
related with #358
=> Migrate 'karton' attribute into new KartonAnalysis objects

mwdb/resources/user.py, mwdb/web/src/components/Settings/Views/UserDetails.js
Possibility of self-block.
Prevent self-block and block user by accident. Now to block user you have to confirm that action in modal.
**Test plan**
Try to block yourself and block some users.
closes #379
=> Prevent self-block

mwdb/core/capabilities.py
**Test plan**
Down and rebuild project container, and check if admin has all capabilities set by default.
closes #384
=> Fix missing removing_attributes capability

mwdb/web/src/commons/config/provider.js, mwdb/web/src/components/Navigation.js, mwdb/web/src/components/Settings/SettingsView.js, mwdb/web/src/components/Settings/Views/UsersPendingList.js
Pending user count is refreshed from time to time, updating its value.
Now its value is still refreshed in from time to time, but in UsersPendingList component its is forced refreshed to change its value after accepting or rejecting user.
**Test plan**
Create some pending users, and check count badges after accepting or rejecting them
closes #272
=> Improved counting of pending users

mwdb/web/src/commons/ui/index.js, mwdb/web/src/components/Settings/Views/GroupDetails.js, mwdb/web/src/components/Settings/Views/GroupsList.js, mwdb/web/src/components/Settings/Views/UserDetails.js, mwdb/web/src/components/Settings/Views/UsersList.js
- `GroupsList`/`UsersList` are hard to read when there are multiple member elements
- `GroupDetails`/`UserDetails` are using simple badge instead of unified `GroupBadge`
**Test plan**
Check if changed components still work
=> UI: GroupsList and UsersList improvements

mwdb/resources/group.py, mwdb/web/src/commons/api/index.js, mwdb/web/src/commons/ui/FeatureSwitch.js, mwdb/web/src/commons/ui/index.js, mwdb/web/src/components/Settings/Views/AccessControl.js, mwdb/web/src/components/Settings/Views/AttributeDetails.js, mwdb/web/src/components/Settings/Views/GroupDetails.js, mwdb/web/src/components/Settings/Views/GroupView.js
- Added feature switch for groups
- Transformed 'hidden' attribute EditableItem into FeatureSwitch
closes #367
=> UI: Default and workspace setting for groups

mwdb/web/src/App.js, mwdb/web/src/components/Navigation.js, mwdb/web/src/components/Profile/Views/ProfileDetails.js, mwdb/web/src/components/Profile/Views/ProfileGroup.js, mwdb/web/src/components/Settings/SettingsView.js, mwdb/web/src/components/Settings/Views/AccessControl.js, mwdb/web/src/components/Settings/Views/AttributeCreate.js, mwdb/web/src/components/Settings/Views/AttributeDetails.js, mwdb/web/src/components/Settings/Views/AttributePermissions.js, mwdb/web/src/components/Settings/Views/AttributeView.js, mwdb/web/src/components/Settings/Views/AttributesList.js, mwdb/web/src/components/Settings/Views/GroupCreate.js, mwdb/web/src/components/Settings/Views/GroupDetails.js, mwdb/web/src/components/Settings/Views/GroupMembers.js, mwdb/web/src/components/Settings/Views/GroupView.js, mwdb/web/src/components/Settings/Views/GroupsList.js, mwdb/web/src/components/Settings/Views/UserCreate.js, mwdb/web/src/components/Settings/Views/UserDetails.js, mwdb/web/src/components/Settings/Views/UserResetPassword.js, mwdb/web/src/components/Settings/Views/UserSingleGroups.js, mwdb/web/src/components/Settings/Views/UserView.js, mwdb/web/src/components/Settings/Views/UsersList.js, mwdb/web/src/components/Settings/Views/UsersPendingList.js
/admin as base path to settings section
/admin changed to /settings
**Test plan**
Test all linked components with settings section
=> Change base path to settings section

mwdb/web/src/components/Profile/Views/ProfileCapabilities.js
Capability table is weird.
Capability table is looks nicer.
**Test plan**
:thinking: 
Before:
After:
=> web/profile: Make capability table more readable

mwdb/web/src/components/Profile/Views/ProfileGroup.js, mwdb/web/src/components/Profile/Views/ProfileGroupMembers.js, mwdb/web/src/components/Settings/Views/GroupDetails.js, mwdb/web/src/components/Settings/Views/GroupMembers.js, mwdb/web/src/components/Settings/Views/UserDetails.js, mwdb/web/src/components/Settings/Views/UserSingleGroups.js
Sorted data related to MemberLists component inside Settings and Profile pages,
and sorted in the same way badges in Group or User details.
**Test plan**
Check the sort order
closes #397
=> UI: Sort Group/Members columns in profile and settings page

mwdb/web/src/components/Settings/Views/SettingsOverview.js
- `Rate limits` feature status is incorrectly reported in https://mwdb.cert.pl/settings page
- Issue is fixed
closes #393
=> Fixed typo that caused incorrect Rate limits feature status

mwdb/model/object.py
- Karton attributes are arbitrary ordered
- Karton attributes are in the same order as other attributes.
closes #403
=> Fix unordered 'karton' attribute values

docs/conf.py, mwdb/version.py, mwdb/web/package-lock.json, mwdb/web/package.json, mwdb/web/src/commons/package.json, setup.py
There are no significant issues with current RC, so we can mark this release as stable :tada:
=> Bump version: 2.3.0 (stable release)

mwdb/web/src/App.js, mwdb/web/src/commons/ui/NavDropdown.js, mwdb/web/src/components/RecentView/RecentView.js, mwdb/web/src/components/RecentView/RecentViewList.js
There are multiple issues with RecentView component:
- Number of results does not display after making a query via URL or refreshing the view (https://github.com/CERT-Polska/mwdb-core/issues/404)
- Quick query can be added when incorrect query was passed via URL
Changed life cycle of RecentView component by swapping `currentQuery` and `submittedQuery` semantics:
Before:
- User submits query by changing submittedQuery state
- Changed submittedQuery state triggers API request for count of results
- When count is evaluated and query was parsed correctly by backend, view navigates to `/<pathname>?q=<query>` and RecentView starts fetching pages with results
After:
- User submits query by …
=> UI: Fixed issues with RecentView component

mwdb/model/object.py, mwdb/resources/metakey.py, mwdb/schema/metakey.py
- We can't remove all values under the same key if some values are too long
- `value` argument in `DELETE /api/{type}/{identifier}/meta` is now optional. If user pass empty value to this argument, all values under the specified key will be removed
**Test plan**
- Check if single value removal still works
- Check if all values can be removed
Requested by @catsuryuu
=> Remove all object attributes by key

docs/conf.py, mwdb/version.py, mwdb/web/package-lock.json, mwdb/web/package.json, mwdb/web/src/commons/package.json, setup.py
Small release that includes minor improvements of existing features.
**New features and improvements:**
- API keys have names in addition to UUID identifier, so user can describe the purpose of API key (https://github.com/CERT-Polska/mwdb-core/pull/420)
- Web: DagreD3Plot and SwaggerUI components are lazy-loaded, so the main JS bundle is much smaller. This should boost the loading time of MWDB webapp (https://github.com/CERT-Polska/mwdb-core/pull/418, https://github.com/CERT-Polska/mwdb-core/pull/427)
- User can delete all attributes under the same key via single API request. This is mainly a workaround for deletion of attribute values that are too long for URI query part of `DELETE` request. (https://github.com/CERT-Polska/mwdb-core/pull/426)
**Bugfixes:**
- Web: Multiple bugfixes in …
=> Bump version: 2.4.0

mwdb/model/object.py, mwdb/resources/karton.py
…lysis_id}  endpoint
No parameters information for endpoint PUT /api/{type}/{identifier}/karton/{analysis_id}
Added parameters information for endpoint PUT /api/{type}/{identifier}/karton/{analysis_id}
Cover issue #453 
closes #453
=> PUT /api/{type}/{identifier}/karton/{analysis_id} endpoint parameters and bugfix

mwdb/web/src/components/Navigation.js, mwdb/web/src/components/OAuth.js
Better oauth authentication login view
**Test plan**
Check if you are able to sing in by oauth provider
=> Oauth login view

docs/index.rst, docs/oauth-guide.rst, docs/setup-and-configuration.rst
Simple docs for OpenID Connect beta feature.
=> Docs: OpenIDConnect

mwdb/web/src/App.js, mwdb/web/src/components/ShowObject/Views/SharesBox.js
Lock icon that shows current object sharing state appearing in different colors in shares section.
**Test plan**
Share private and public some object.
part #488
=> Simply sharing state visualization

.github/workflows/build.yml, .github/workflows/release.yml
=> CI: Include cache metadata in Docker Hub pushes

mwdb/web/src/components/ShowObject/Views/CommentBox.js
Words at end of lines  in comment component are split into two lines.
Words are not split into two lines.
**Test plan**
closes #507
=> Add overflow-wrap to comment style

.github/workflows/release.yml
Doesn't apply to the MWDB itself
We use [Git context](https://github.com/docker/build-push-action#git-context) in build-push-action that somehow doesn't work correctly and fails silently with release event, producing empty images.
```
#1 [internal] load git source https://github.com/CERT-Polska/mwdb-core.git#f7276d0c88d69331127222eeadb876b6ad038617
#1 0.092 hint: Using 'master' as the name for the initial branch. This default branch name
#1 0.092 hint: is subject to change. To configure the initial branch name to use in all
#1 0.092 hint: of your new repositories, which will suppress this warning, call:
#1 0.092 hint: 
#1 0.092 hint: 	git config --global init.defaultBranch <name>
#1 0.092 hint: 
#1 0.092 hint: …
```
=> CI: Fix release builds

docker/mwdb.ini, mwdb/core/config.py, mwdb/resources/server.py, mwdb/schema/server.py, mwdb/web/src/components/Navigation.js
Hardcoded local instance name in Navigation.js
Allow to change intance name in mwdb configuration.
**Test plan**
Change instance_name in docker/mwdb.ini
partial #415
=> Custom instance name

deploy/docker/Dockerfile, requirements.txt, setup.py
- Flask and related dependencies are a bit old so we're forced to use older versions of dependencies
- Bumped Flask and related dependencies to the latest version
- Dropped support for Python 3.6
**Test plan**
Most important things should be covered by automated tests
=> Bump Flask to 2.x.x

requirements.txt
Karton-core version is updated to the latest version
**Test plan**
=> Bump Karton version

docs/setup-and-configuration.rst
=> doc: Document missing config settings

requirements.txt
Described in #543.
`itsdangerous` is pinned to the 2.0.1 version that works with current version of MWDB Core.
**Test plan**
Should be covered by automated tests.
=> Pin itsdangerous dependency to 2.0.1

docker-compose.yml, docs/conf.py, mwdb/version.py, mwdb/web/package-lock.json, mwdb/web/package.json, mwdb/web/src/commons/package.json, setup.py
Changes version from v2.6.0 to v2.6.1
=> [v2.6.x] Bump to v2.6.1 version

requirements.txt
- Backported dependencies bump from:
- https://github.com/CERT-Polska/mwdb-core/pull/544
- https://github.com/CERT-Polska/mwdb-core/pull/534
- https://github.com/CERT-Polska/mwdb-core/pull/532
**Test plan**
Change should be covered by automated tests
closes #543
=> [v2.6.1] Bump Flask and Karton dependencies

requirements.txt
Backport of https://github.com/CERT-Polska/mwdb-core/pull/544
Closes https://github.com/CERT-Polska/mwdb-core/issues/543
=> [v2.6.1] Pin itsdangerous dependency to 2.0.1

mwdb/web/src/components/Upload.js
Upload.js doesn't allow for extensions.
We can extend the upload component to allow for other forms of upload.
**Test plan**
Extend it and check the results.
=> Make upload form extendable

mwdb/web/package-lock.json, mwdb/web/package.json
- `react-bootstrap` is not used by Web part but stays in `package.json`
- Removed `react-bootstrap` from `package.json`
=> Web: removed unused react-bootstrap dependency

mwdb/model/object.py
Explained in #574 
`assign_analysis` method is protected from race condition due to analysis assigned in concurrent transaction
**Test plan**
Should be covered by automated tests
closes #574
=> Fix ix_karton_analysis_object UniqueViolation error

mwdb/model/object.py, tests/backend/test_relations.py
Disappearing all object permissions when removing cycling relationship
Don't touch object permissions in the case of cycle relation remove
**Test plan**
Create some cycle relation to object and remove it. Check if permissions still exixst.
closes #575
=> Fix removing cycle relationship

mwdb/app.py, mwdb/model/file.py, mwdb/resources/file.py, mwdb/web/src/App.js, mwdb/web/src/commons/api/index.js, mwdb/web/src/components/Remote/RemoteAPI.js, mwdb/web/src/components/ShowObject/Actions/ZipAction.js, mwdb/web/src/components/ShowObject/index.js, mwdb/web/src/components/ShowSample.js, requirements.txt
This feature allow you to download file as zip archive.
**Test plan**
Check if api works properly and you are able to download file as zip archive.
closes #583
=> Download zipped files feature

docker-compose.yml, docs/conf.py, mwdb/version.py, mwdb/web/package-lock.json, mwdb/web/package.json, mwdb/web/src/commons/package.json, setup.py
Version bump because master branch contains new features.
=> Bump version: v2.8.0

mwdb/web/src/commons/ui/MemberList.js
pagination bar appears but froup members are not paginated
Paginated MemberList with "add member" button on the top of it
**Test plan**
Check if pagination works properly in group members view and user groups view.
closes #585
=> Fix pagination in MemberList

mwdb/web/src/commons/ui/Tag.js
- Tags are class-based components
- Contain `#` links as buttons which are considered incorrect
- Rewritten to function-based component
- Converted `#` link to `span` with button role and proper styling.
**Test plan**
Check if tags are still working and looking the same as before
=> Tag refactor: function-based component and correct remove button

requirements.txt
Using an outdated version of karton-core
Uses the new version of karton-core
**Test plan**
Current test suite doesn't break.
N/A
=> Bumping Karton-core to 4.4.1

mwdb/web/src/commons/ui/PagedList.js
Legacy component
Refactored component
**Test plan**
Check all settings view
=> UI Refactor: PagedList

mwdb/web/src/commons/ui/SortedList.js
Legacy component
Refactored Component
**Test plan**
Go to statistics
=> UI refactor: SortedList

mwdb/web/src/components/ConfigStats.js
Legacy class component
Refactored component to hooks
**Test plan**
Test config stats component
=> UI refactor: ConfigStats

mwdb/web/src/components/UserRegister.js
Legacy class component.
Refactored functional component based on hooks
**Test plan**
Try to register
=> UI Refactor: UserRegister.js

mwdb/web/src/commons/ui/Identicon.js
Legacy class based component
Refactored functional component based on hooks
**Test plan**
Check identicon in object view
=> UI refactor: Identicon.js

mwdb/web/package.json, mwdb/web/src/components/UserSetPassword.js
Very legacy UserSetPassword component
Totally refactored UserSetPassword component with the use of yup and reack-hook-form
**Test plan**
Test new component by changing password for test user
=> UI refactor: UserSetPassword

mwdb/web/src/components/UserPasswordRecover.js
Legacy class based component
Refactored functional component based on hooks
**Test plan**
Try to request for recover password reset link
=> UI Refactor: password recover

mwdb/web/src/App.js, mwdb/web/src/components/Upload.js
Legacy class based component
Functional component based on react hooks
**Test plan**
Check upload view with various options of uploading file.
=> UI refactore: Upload.js

.github/workflows/build.yml, pyproject.toml
**What is the current/new behaviour?**
- Use new version of lint-python-action, enabling to use `lint-python` tool
=> Use lint-python-action@v2

mwdb/web/src/components/ShowSample.js
- Hex/Raw switch doesn't work after refactor because callback was passed instead of simple string
- Switch works
=> Fix sample preview hex/raw switch button

mwdb/web/src/commons/ui/HexView.js
Legacy class based component
Functional component based on react hooks
**Test plan**
Check hex view
=> UI refactore: HexView.js

mwdb/web/src/components/ShowObject/Views/CommentBox.js
Chaotic comment section
Improved comments section
**Test plan**
Pass same comments to example object
closes #643
=> Simply revamp comments section

mwdb/web/src/components/DiffTextBlob.js
Legacy components based on hooks
Refactored components with the use of react hooks inside DiffTextBlob.js
**Test plan**
Check if refactored compoents works properly
closes #614
=> UI refactor: DiffTextBlob.js

mwdb/web/src/components/About.js
- Cert.pl is mentioned, but not clickable
- The version number is displayed, but not clickable
- Cert.pl is mentioned and clickable
- The version number is displayed and clickable, leading to the release notes.
=> Add some links on the about page

mwdb/web/package-lock.json
`package-lock.json` is not synced with `package.json`
Added missing entries via `npm install --package-lock-only`
=> Fix missing package-lock entries: yup, react-hook-form

mwdb/web/src/components/RichAttribute/MarkedMustache.js, mwdb/web/src/components/RichAttribute/RichAttributePreview.js, mwdb/web/src/components/ShowObject/Views/Attributes.js
- Added object context to Mustache view
- Correct search for string values that have rich template
- Removed unnecessary margins on list and paragraph elements
- Renamed `Delete` button to `Clear`
**Test plan**
Manual tests if rich attributes work correctly
=> Rich attributes: missing things and improvements

docker-compose.yml, docs/conf.py, mwdb/version.py, mwdb/web/package-lock.json, mwdb/web/package.json, mwdb/web/src/commons/package.json, setup.py
Bump version to v2.8.2 on v2.8.x patch release branch
=> Bump version: v2.8.2

docker-compose-dev-karton.yml, mwdb/model/file.py
Backport of #695 to v2.8.x branch
=> Backport: Fix pre-download file from S3 to TemporaryFile on File.open

mwdb/model/object.py, tests/backend/test_permissions.py
Backport of #702 to v2.8.x branch
=> Backport: Fix deleting objects with comments

mwdb/core/util.py
`iam_auth` doesn't work. `boto3.client("iam"` returns IAM management service instead of S3 client.
Use InstanceMetadataProvider to fetch credentials from EC2 instance metadata.
**Test plan**
Check on EC2 instance if it works correctly.
Current approach might be not really efficient because provider is created every time we call get_s3_client. We should keep it globally to cache credentials within worker.
closes #698
=> S3: Fix authentication via IAM (iam_auth)

docker-compose-dev.yml, mwdb/web/config-overrides.js
Webpack config uglifies every instance of app
Webpack config uglifies only production instance of app.
Development app is non-uglified.
**Test plan**
=> conditional uglification

mwdb/web/src/App.js, mwdb/web/src/components/Navigation.js, mwdb/web/src/components/OAuth.js, mwdb/web/src/components/UserLogin.js, mwdb/web/src/styles/index.css, tests/frontend/cypress/integration/util.js
Front-end for OAuth authentication might look better
Front-end for OAuth authentication looks better
When there aren't any OAuth providers
When there is at least one but not more that 5 providers
When there are 6 OAuth providers or more
**Test plan**
Visual tests
closes #728
=> Improve auth frontend

mwdb/web/src/components/AttributesAddModal.js, mwdb/web/src/components/RichAttribute/RichAttributePreview.js, mwdb/web/src/components/RichAttribute/RichAttributeRenderer.js
When you add rich attribute to object you can check its value only after submit it.
New component RichttributeRenderer.js that allow to render rich attribute value dynamically.
Use that implementation in AttributesAddModal.js that allow us to preview and check rich value before submitting new attribute.
**Test plan**
Define rich attribute template.
Check if you could add rich attribute value to the object.
If template and AttributesAddModal works properly.
closes #621
=> Rich preview in AttributeAddModal

mwdb/web/src/components/RecentView/RecentView.js
Shadow after click count button
Removed shadow from count button in RecentView.js and added tooltip message to it.
**Test plan**
Check if count button properly work
=> UI Improvement: count button

tests/backend/test_api.py
We shouldn't check emptiness of parents/children/tags in `test_search`. It's pointless and makes test flaky because `karton-classifier` and `karton-mwdb-reporter` asynchronously add tag information.
Removed flaky assertions.
**Test plan**
closes #738
=> Fix flaky test_search

mwdb/web/src/commons/remotes/index.js
Can't switch to other instance view than main view
Improve useRemote function for better matching the remote instance name in URL path.
**Test plan**
Setup mwdb-core with remote instance and check if Links lead to proper remote Views.
closes #737
=> Fix: remote instance path

mwdb/web/src/components/ShowObject/Views/ObjectBox.jsx
Bad generated pathnames in object tabs link couse problem with rendering all components in object view.
Changed the bahaviour of ObjectBox.js compoenent for properly work with remote pathes.
**Test plan**
Check if remote instances works fine.
closes #737
=> Fix: Object view in remote instances

mwdb/web/src/components/OAuth.jsx, mwdb/web/src/components/UserLogin.jsx
Registration using OAuth IS NOT available in front-end.
Registration using OAuth IS available in front-end.
**Test plan**
Manual
=> Register using OAuth in front-end

mwdb/web/src/components/UserLogin.jsx
When more then 1 tab with application is open, and you login on one of them, other will crash.
Login on all tab simultaneously without crash.
**Test plan**
closes #779
=> Fix crashing other tabs on login

mwdb/web/src/components/ShowObject/Views/SharesBox.jsx
Shares in config and blob view are presented in `Inherited shares` box 
Shares in config and blob view are presented in `Shares` box 
**Test plan**
Manual
closes #788
=> fix sharesBox for configs and blobs

mwdb/web/src/components/UserLogin.jsx
Remove toast that appers after log in into mwdb
=> Remove info about log in

mwdb/web/src/commons/ui/ErrorBoundary.jsx
On error accrued user get only information what is the problem for example: missing variable or missing import
Now user get information not only what is a problem, but also where is a problem.
**Test plan**
closes #687
=> add stack information to ErrorBoundary component

mwdb/web/src/components/ShowObject/Actions/RemoveAction.jsx
No information after the object removal action
Add toast that appears after successful remove object action.
**Test plan**
Check code and improvement.
=> UI: Object removal message

docker-compose-dev-karton.yml
When using `docker-compose -f docker-compose-dev-karton.yml up` you have to create `mwdb` bucket manually
The `mwdb` bucket is created automatically
**Test plan**
Manual tests
closes #764
=> Create MWDB bucket with docker-compose-dev-karton

mwdb/web/src/components/ShowObject/Views/RelationsBox.jsx, mwdb/web/src/styles/index.css
=> Add icons to relations box

docs/setup-and-configuration.rst
It is NOT said that `MWDB` and `karton` should have separate buckets
It is said that `MWDB` and `karton` should have separate buckets
closes #747
=> Update docs about buckets for karton and mwdb

mwdb/web/src/components/Profile/Views/ProfileAPIKeys.jsx
When you add new api you get an error.
You can add new api
**Test plan**
closes #817
=> Fix adding api key

mwdb/web/src/commons/api/index.tsx, mwdb/web/src/types/api.ts
- `EnableSharing3rdPartyResponse` has typo
- `ServerInfoResponse` describes response for `/ping` instead of `/server`
Fixed issues
**Test plan**
manual
none
=> Web: Fix ServerInfoResponse and EnableSharing3rdPartyResponse

mwdb/web/vite.config.ts
Described in issue.
closes #826
=> Web: resolve only plugins with name that matches specific pattern

mwdb/core/karton.py, requirements.txt
Bumped Karton to v5.1.0 adding support for extended service information.
**Test plan**
Main things should be covered by automated tests
none
=> Bump Karton to v5.1.0

mwdb/web/src/App.jsx, mwdb/web/src/commons/auth/capabilities.tsx, mwdb/web/src/commons/auth/index.tsx, mwdb/web/src/commons/auth/provider.tsx, mwdb/web/src/components/Navigation.jsx, mwdb/web/src/components/Profile/Views/ProfileCapabilities.jsx, mwdb/web/src/components/Profile/Views/ProfileDetails.jsx, mwdb/web/src/components/Profile/Views/ProfileGroup.jsx, mwdb/web/src/components/Profile/Views/ProfileGroupMembers.jsx, mwdb/web/src/components/RecentView/QuickQuery.jsx, mwdb/web/src/components/ShowObject/Actions/FavoriteAction.jsx, mwdb/web/src/components/ShowObject/Actions/RemoveAction.jsx, mwdb/web/src/components/ShowObject/Actions/UploadChildAction.jsx, mwdb/web/src/components/ShowObject/Views/AttributesBox.jsx, mwdb/web/src/components/ShowObject/Views/CommentBox.jsx, mwdb/web/src/components/ShowObject/Views/KartonAnalysisBox.jsx, mwdb/web/src/components/ShowObject/Views/RelationsBox.jsx, mwdb/web/src/components/ShowObject/Views/Share3rdPartyBox.jsx, mwdb/web/src/components/ShowObject/Views/TagBox.jsx, mwdb/web/src/components/Upload.jsx, mwdb/web/src/types/types.ts
Applies to #810 as a suggestion
=> Change proposal to #810: Make enum from Capability type

mwdb/core/karton.py
Karton was instantiated after https://github.com/CERT-Polska/mwdb-core/pull/829 even if Karton was not configured and not enabled. Before #829 it was created lazily.
Karton is instantiated only when Karton is enabled.
=> Fix: Don't instantiate KartonProducer when Karton is not enabled

mwdb/web/src/commons/api/index.tsx, mwdb/web/src/components/RecentView/Views/RecentViewList.tsx, mwdb/web/src/components/Remote/RemoteAPI.tsx, mwdb/web/src/components/Remote/RemoteViews.tsx, mwdb/web/src/types/context.ts
=> TS: add types to components/remote

mwdb/web/src/components/AttributesAddModal.tsx
Selecting an attribute from the list doesn't do anything
Select works as in previous versions
**Test plan**
Add attribute, select it, add it
=> Fix: selecting attribute from list when adding new attribute

mwdb/web/src/commons/helpers/getErrorMessage.tsx, mwdb/web/src/components/RecentView/Views/RecentView.tsx
Temporary network issues result in obscure error
Errors are correctly handled by component trying to make a request
=> Fix NetworkError handling in RecentView and getErrorMessage

dev/bump_version.json, docker-compose.yml, docs/conf.py, mwdb/version.py, mwdb/web/package-lock.json, mwdb/web/package.json, requirements.txt, setup.py
Docker image doesn't built correctly because Cython 3.x release breaks older versions of PyYAML
Bumped PyYAML to v6.0.1
**Test plan**
Check if project builds and starts correctly
closes #855
=> Bump PyYAML to 6.0.1

mwdb/app.py
=> Log: include PID and before_request log for debugging

mwdb/web/src/components/Views/UploadView.tsx
Cannot change parent field in upload view
Now parent input field can be edited when param parent in url is not empty
**Test plan**
closes #877
=> fix parent input field in uploadView

mwdb/web/src/commons/config/provider.tsx
explained in https://github.com/CERT-Polska/mwdb-core/issues/897#issuecomment-1921257486
closes #897
=> Web: Fix race condition with applying request_timeout value

docker-compose.yml, docs/conf.py, docs/index.rst, docs/prometheus-guide.rst, docs/requirements.txt, docs/setup-and-configuration.rst, docs/whats-changed.rst, mwdb/version.py, mwdb/web/package-lock.json, mwdb/web/package.json, setup.py
- ~~[ ] I've tested my changes by building and running the project, and testing changed functionality (if applicable)~~
- ~~[ ] I've added automated tests for my change (if applicable, optional)~~
=> Bump and docs: v2.12.0

mwdb/model/karton.py, requirements.txt
Karton endpoints use inefficient method of gathering analysis status
Karton is upgraded to v5.4.0 and new get_analysis method is used. To get significant performance gain, karton-system must be upgraded to v5.4.0 as well.
=> Upgrade karton to v5.4.0 and use get_analysis method

mwdb/core/search/mappings.py
**Test plan**
Build and query for `blob:"whatever"`
closes #956
=> Fix internal server error when querying without field

docker-compose-oidc-dev.yml, mwdb/resources/oauth.py
Issue is well described in https://github.com/CERT-Polska/mwdb-core/issues/964.
Tested manually. Closes #964
=> OIDC: Fetch userinfo claims from userinfo endpoint

mwdb/web/src/components/RecentView/Views/RecentView.tsx
=> Fix: 'Back' doesn't work in RecentView because of navigation loop

mwdb/web/src/styles/index.css
=> Fix tag visibility in relation graph #1011

mwdb/web/package-lock.json, mwdb/web/package.json
Smarter bump than https://github.com/CERT-Polska/mwdb-core/pull/1041
=> web: Bump vite to v6

docs/rich-attributes-guide.rst, mwdb/web/src/components/RichAttribute/builtinLambdas.tsx
`jsonify` is not enough for making own searchable values if value contains spaces. It needs to be URI-encoded as well.
Added `uriencode` transformer and proper documentation notes.
=> Add transformer lambda: uriencode

mwdb/web/src/commons/ui/ConfirmationModal.tsx
**What is the current/new behaviour?**
See also https://github.com/CERT-Polska/mwdb-core/pull/1053#issuecomment-3132694003
In https://github.com/CERT-Polska/mwdb-core/pull/1044 I have set `maxHeight: 80%` on modal content to solve the problem of overflowing modal when content height is too big. react-modal sets `overlow: auto` internally (https://github.com/reactjs/react-modal/blob/7a2a63c91c879b8c34969bc418d8c395ac45167e/src/components/Modal.js#L123) so this should enforce modal to show the scroll bars.
Unfortunately, some 3rd party plugins are not showing the expected scroll bars in their modals, but they used to render correctly without `maxHeight` limitation.  In the same time, the `maxHeight: 80%` value is a bit low and leaves lot of empty …
=> Update ConfirmationModal.tsx: set maxHeight to 100%

mwdb/web/src/commons/ui/NavDropdown.tsx, mwdb/web/src/commons/ui/ObjectTab.tsx, mwdb/web/src/components/Blob/Views/ShowTextBlobView.tsx, mwdb/web/src/components/Config/Views/ShowConfigView.tsx, mwdb/web/src/components/ShowObject/common/RelationsTab.tsx, mwdb/web/src/components/Views/ShowSampleView.tsx, mwdb/web/tsconfig.json
Object actions render in the bar one after another, which causes ugly navigation rendering in the object view at lower resolutions or even at full HD with all available actions.
Actions have been moved to an expandable dropdown, making it easier to navigate through the available actions on the object.
**Test plan**
Test dropdown on all type of objects.
=> UI: Add actions dropdown in ObjectTab
